/* Decision controls and model integration in a VM DOM fixture. Not rendered browser QA. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(process.argv[2]||path.join(__dirname,'../prototype'));
let checks=0;
const check=(pass,reason)=>{assert.ok(pass,reason);checks++};
function create(savedString=null){
 const elements=new Map(),handlers={},storage=new Map(),writes=[],mutations=[];let storageFails=false;
 if(savedString)storage.set('citymeter-yolk-public-demo-v1',savedString);
 const element=key=>{if(!elements.has(key)){let html='',outer='';elements.set(key,{dataset:{},value:'',textContent:'',disabled:false,selectionStart:0,classList:{add(){},remove(){},toggle(){}},setAttribute(){},showModal(){},close(){},focus(){document.activeElement=this},scrollIntoView(){},get innerHTML(){return html},set innerHTML(value){html=value;mutations.push({key,type:'inner'})},get outerHTML(){return outer},set outerHTML(value){outer=value;mutations.push({key,type:'outer'})}})}return elements.get(key)};
 const shares=[];
 const document={documentElement:{lang:'th',dataset:{},style:{}},activeElement:null,title:'',querySelector:k=>['[data-location-map]','#poi-form','#target-form','#branch-province'].includes(k)?null:element(k),querySelectorAll:k=>k==='[data-weight-share]'?shares:[],addEventListener(type,fn){(handlers[type]??=[]).push(fn)}};
 const context=vm.createContext({document,location:{hash:'#criteria'},localStorage:{getItem:k=>storage.get(k)||null,setItem(k,v){if(storageFails)throw Error('fixture storage full');storage.set(k,v);writes.push([k,v])}},structuredClone,crypto:crypto.webcrypto,clearTimeout(){},setTimeout(){return 0},addEventListener(){},scrollTo(){},console,FormData:class{constructor(f){this.v=f.values||{}}[Symbol.iterator](){return Object.entries(this.v)[Symbol.iterator]()}},MouseEvent:class{}});context.window=context;
 const load=['theme.js','icons.js','data/thailand-provinces.js','data/demo-data.js','metrics.js','model.js','landscape.js','leaderboard.js','supply-ui.js','data/demo-map-context.js','location-map.js','branch-photos.js','decision-ui.js','app.js'];
 for(const file of load)vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file});
 const run=source=>vm.runInContext(source,context);
 for(const scope of ['rankingWeights','demandGroupWeights','metricWeights'])for(const key of run(`Object.keys(draft.${scope})`))shares.push({dataset:{weightShare:scope+':'+key},textContent:''});
 const dispatch=(type,target)=>{for(const handler of handlers[type]||[])handler({target,preventDefault(){}})};
 const inputWeight=(scope,key,value)=>{const e=element('#weight-'+scope+'-'+key);e.value=String(value);e.dataset={weightScope:scope,weightKey:key};document.activeElement=e;dispatch('input',e);return e};
 const change=(id,value)=>{let e=element('#'+id);e.id=id;e.value=String(value);e.dataset={};dispatch('change',e)};
 const click=action=>{const button={dataset:{action},disabled:false};dispatch('click',{closest:()=>button})};
 return {run,context,document,element,dispatch,inputWeight,change,click,shares,mutations,writes,storage,failStorage(value=true){storageFails=value}};
}
const ui=create(),run=ui.run;
const expected=[['Crowded',true,true,true],['FOMO',true,true,false],['Our Farm',true,false,true],['Pioneer',true,false,false],['Quiet',false,false,false],['Their War',false,true,false],['Our Island',false,false,true],['Winter War',false,true,true]];
check(run('JSON.stringify(YolkDecisions.patterns.map(p=>[p.name,p.d,p.c,p.b]))')===JSON.stringify(expected),'all eight cards encode the model truth table in D/C/B order');
for(const lang of ['th','en']){
 run(`Y.lang='${lang}'`);
 const html=run('YolkDecisions.preferred()');
 check((html.match(/data-pattern=/g)||[]).length===8,`${lang}: all eight types have selectable cards`);
 check((html.match(/class="pattern-levels"/g)||[]).length===8,`${lang}: each card shows Demand, competitors and Bangchak levels`);
 check((html.match(/class="pattern-description"/g)||[]).length===8,`${lang}: every type has explanatory copy`);
 check((html.match(/class="pattern-filter-note"/g)||[]).length===4,`${lang}: low-demand types explain the active high-only filter`);
 check((html.match(/≥ 3|< 3/g)||[]).length===16,`${lang}: every card shows both current supply cutoffs`);
 const supply=run('supplyControls()'),criteria=run('criteria()');
 check(!supply.includes('data-pattern')&&!supply.includes('preferred-fieldset'),`${lang}: preferred types are separate from Supply`);
 check(criteria.indexOf('id="preferred-types"')>criteria.indexOf(supply)+supply.length-1,`${lang}: Preferred section follows the closed Supply section`);
 const row=run('placeRow(evaluate().find(a=>a.eligible),0)');
 check(/<button class="btn view-details"[^>]*data-action="place"/.test(row)&&row.includes('data-yolk-glyph="location_on"')&&row.includes(lang==='th'?'ดูรายละเอียด':'View details'),`${lang}: details is a labelled button with an icon`);
 check(!row.includes('Evidence & work'),`${lang}: ambiguous former link is gone`);
 check(run('YolkDecisions.rankLabel()')===(lang==='th'?'คะแนนตามน้ำหนัก / 100':'Weighted score / 100'),`${lang}: ranking labels match weighted scores`);
}
run("Y.lang='en';render();YolkDecisions.sync()");
const share=(scope,key)=>ui.shares.find(e=>e.dataset.weightShare===scope+':'+key).textContent;
check(share('rankingWeights','demand')==='70.0%'&&share('rankingWeights','ownGap')==='20.0%'&&share('rankingWeights','competitorGap')==='10.0%','overall weight percentages normalize independently');
check(share('demandGroupWeights','building')==='50.0%'&&share('demandGroupWeights','activity')==='50.0%','disabled extra group is excluded from group normalization');
check(share('metricWeights','gfa')==='33.3%'&&share('metricWeights','factory_count')==='16.7%','metric percentage denominator is its own enabled group');
const baseline=run('JSON.stringify(evaluate(Y.criteria).filter(a=>a.eligible).map(a=>a.id))'),baselineSet=run('JSON.stringify(evaluate(Y.criteria).filter(a=>a.eligible).map(a=>a.id).sort())');
const fullWrites=ui.mutations.filter(x=>x.key==='#content').length;
ui.inputWeight('rankingWeights','demand',0);ui.inputWeight('rankingWeights','ownGap',100);const focused=ui.inputWeight('rankingWeights','competitorGap',0);
check(run('JSON.stringify(evaluate(draft).filter(a=>a.eligible).map(a=>a.id).sort())')===baselineSet,'weight input preserves the screened membership');
check(run('JSON.stringify(evaluate(draft).filter(a=>a.eligible).map(a=>a.id))')!==baseline,'weight input updates ranked order');
check(run('Y.criteria.rankingWeights.demand===70&&draft.rankingWeights.demand===0&&Y.events.length===0'),'weight edits stay private until Apply');
check(ui.mutations.filter(x=>x.key==='#content').length===fullWrites&&ui.document.activeElement===focused&&focused.value==='0','weight preview retains active input instead of rebuilding the whole form');
check(ui.element('#impact-preview').innerHTML.includes('Weights alone keep the same qualifying set')&&ui.element('#impact-preview').innerHTML.includes('previously eligible locations change rank'),'impact preview explains changed ranks separately from membership');
check(share('rankingWeights','ownGap')==='100.0%'&&share('rankingWeights','demand')==='0.0%','input refreshes normalized component percentages');
ui.click('apply-criteria');
check(run('Y.criteria.version===2&&Y.events.length===1&&Y.events[0].type==="criteria.updated"&&Y.events[0].recipients.length===9'),'apply commits one workspace criteria event and increments version once');
check(run('JSON.stringify(Y.events[0].changes.map(c=>c.field).sort())')===JSON.stringify(['rankingWeights.competitorGap','rankingWeights.demand','rankingWeights.ownGap']),'feed records each changed overall weight field');
check(run('Y.events[0].changes.every(c=>fieldNames[c.field]&&typeof c.before==="number"&&typeof c.after==="number")'),'weight feed contains human-readable fields and numerical before/after values');
check(ui.element('#content').innerHTML.includes('Weight: demand')&&ui.element('#content').innerHTML.includes('Weight: own branch gap'),'criteria feed renders readable weight labels');
const key=run('STORAGE_KEY'),saved=JSON.parse(ui.storage.get(key));
check(saved.criteria.version===2&&saved.criteria.rankingWeights.ownGap===100&&saved.events[0].changes.length===3,'saved criteria and audit event persist together');
const reload=create(ui.storage.get(key));
check(reload.run('Y.criteria.version===2&&Y.criteria.rankingMode==="weighted"&&Y.criteria.rankingWeights.ownGap===100&&Y.events.length===1'),'reload preserves new weights and event without remigration');
ui.click('apply-criteria');check(run('Y.events.length===1&&Y.criteria.version===2'),'reapplying without a diff creates no duplicate event');
ui.click('reset-draft');ui.change('max-demand-tier',1);
check(run('draft.maxDemandTier===1&&evaluate(draft).filter(a=>a.eligible).length<evaluate(Y.criteria).filter(a=>a.eligible).length'),'tier selector changes screened membership');
ui.change('max-demand-tier',3);check(run('evaluate(draft).filter(a=>a.eligible).length===evaluate(Y.criteria).filter(a=>a.eligible).length'),'widening Tier restores eligible set');
ui.inputWeight('metricWeights','gfa',20);ui.inputWeight('demandGroupWeights','building',80);ui.change('demand-mode','all');
check(run('draft.metricWeights.gfa===20&&draft.demandGroupWeights.building===80&&draft.demandMode==="all"'),'updating Preferred section preserves draft weights');
check(!ui.element('#preferred-types').outerHTML.includes('pattern-filter-note'),'all-demand selection removes high-only explanations from low patterns');
ui.change('ranking-mode','legacy');check(run('draft.metricWeights.gfa===20&&draft.demandGroupWeights.building===80&&draft.rankingMode==="legacy"'),'changing method preserves draft values');
check(ui.element('#ranking-weights').outerHTML.includes('<fieldset disabled>'),'legacy method visibly disables inactive weighting controls');
check(run('YolkDecisions.rankLabel(draft)')==='Peak signal (P)','legacy scores are labelled as signals rather than weighted priority');
ui.click('reset-draft');run("Y.actor='v0';render()");ui.inputWeight('rankingWeights','demand',50);
check(run('draft.rankingWeights.demand===50&&Y.criteria.rankingWeights.demand===0'),'viewer can experiment with draft weights');
check(/data-action="apply-criteria" disabled/.test(ui.element('#impact-preview').innerHTML),'viewer Apply button is disabled');
ui.click('apply-criteria');check(run('Y.criteria.version===2&&Y.events.length===1'),'viewer cannot apply even through dispatched click');
const granular=create();granular.inputWeight('demandGroupWeights','building',80);granular.inputWeight('metricWeights','gfa',20);granular.click('apply-criteria');
check(granular.run('JSON.stringify(Y.events[0].changes.map(c=>c.field).sort())')===JSON.stringify(['demandGroupWeights.building','metricWeights.gfa']),'group and metric changes have separate persisted audit fields');
check(granular.run('Y.events[0].changes.every(c=>fieldNames[c.field])'),'group and metric audit field names are human-readable');
const invalid=create();const blank=invalid.inputWeight('rankingWeights','demand','');
check(invalid.run('criteriaErrors(draft).includes("rankingWeights")')&&invalid.document.activeElement===blank,'blank numeric draft is invalid without discarding the active input');
invalid.click('apply-criteria');check(invalid.run('Y.criteria.version===1&&Y.events.length===0'),'invalid draft cannot be committed');
invalid.inputWeight('rankingWeights','demand',80);invalid.run('Y.criteria.version=2');invalid.click('apply-criteria');
check(invalid.run('Y.criteria.rankingWeights.demand===70&&draft.rankingWeights.demand===80&&Y.events.length===0'),'stale workspace revision prevents commit and keeps draft for review');
// Failed persistence must not look like a successful team change.
const failure=create();failure.inputWeight('rankingWeights','demand',80);failure.failStorage();failure.click('apply-criteria');
check(failure.run('Y.criteria.version===1&&Y.criteria.rankingWeights.demand===70&&Y.events.length===0'),'failed save rolls back team criteria and event');
check(failure.run('draft.rankingWeights.demand===80&&draftBase===1'),'failed save keeps the unsaved draft available for retry');
check(!failure.element('#toast').textContent.includes('Saved'),'failed save does not announce success');
console.log(JSON.stringify({suite:'decisions-v1.4',checks,passed:checks,evidence:'VM/source integration; browser visual and accessibility QA remain separate'}));
