/* Personal analytical views. No criteria writes, area reassignment or team events. */
(function (global) {
 'use strict';
 const views={demand:{kind:'demand',metric:'tier',relation:'own'},supply:{kind:'supply',metric:'count',relation:'total'}};
 const esc=s=>escapeHTML(s),t=(th,en)=>tr(th,en),icon=n=>global.YolkIcons?.icon(n)||'';
 function state(route=Y.route){return views[route==='demand'?'demand':'supply'];}
 function set(key,value){
  const s=state();
  if(key==='relation'&&['own','competitor','total'].includes(value)){if(s.kind==='supply'&&s.metric==='share'&&value!=='total')return false;s.relation=value;}
  else if(key==='metric'&&(s.kind==='demand'||['count','share','market','area'].includes(value))){s.metric=value;if(s.kind==='supply'&&value==='share'){s.relation='total';Y.poiTab='all';Y.page=0;}}
  else return false;return true;
 }
 function metricLabel(s=state()){
  if(s.kind==='demand')return s.metric==='tier'?t('ระดับไข่แดงจากเกณฑ์ Demand','Yolk tier from Demand criteria'):t(METRIC_INDEX[s.metric]?.th||'',METRIC_INDEX[s.metric]?.en||'');
  return s.metric==='share'?t('ส่วนแบ่งสาขาเรา','Our branch share'):s.metric==='count'?t(s.relation==='total'?'จำนวนสาขารวม':s.relation==='own'?'จำนวนสาขาเรา':'จำนวนสาขาคู่แข่ง',s.relation==='total'?'Total branch count':s.relation==='own'?'Our branch count':'Competitor branch count'):s.metric==='area'?t('สาขาต่อพื้นที่','Branches per km²'):t('สาขาต่อฐานตลาด','Branches per market base');
 }
 function formatted(r){if(!r||r.state==='missing'||r.state==='not_applicable')return '—';if(r.kind==='demand'&&r.metric==='tier')return r.exact?'Tier '+r.value:t(r.state==='review'?'รอตรวจ':'ยังไม่ผ่าน',r.state==='review'?'Review':'Below threshold');const n=v=>new Intl.NumberFormat(Y.lang==='en'?'en-US':'th-TH',{maximumSignificantDigits:4}).format(v);if(Number.isFinite(r.value))return n(r.value);if(r.upperOpen&&Number.isFinite(r.lo))return '≥ '+n(r.lo)+' · '+t('ขอบบนยังไม่ทราบ','Upper bound unknown');if(Number.isFinite(r.lo)&&Number.isFinite(r.hi))return n(r.lo)+'–'+n(r.hi);return '—';}
 function unit(r){return t(r?.unitTh||'',r?.unitEn||'');}
 function controls(kind){
  const s=views[kind],supply=kind==='supply',share=s.metric==='share',advanced=['market','area'].includes(s.metric),options=[['count','จำนวนสาขา','Branch count'],['share','ส่วนแบ่งสาขาเรา (%)','Our branch share (%)']];
  if(advanced)options.push(s.metric==='market'?['market','สาขาต่อฐานตลาด','Branches per market base']:['area','สาขาต่อ ตร.กม.','Branches per km²']);
  const relations=supply&&!share?`<div class="analysis-relations" role="group" aria-label="${t('เครือข่ายสาขาบนแผนที่','Map branch network')}">${[['total','O+C','รวมเราและคู่แข่ง','Own + competitors'],['own','O','สาขาเรา','Our stores'],['competitor','C','คู่แข่ง','Competitors']].map(([key,mark,th,en])=>`<button type="button" data-analysis-relation="${key}" aria-pressed="${s.relation===key}">${key==='total'?icon('shield')+icon('swords'):icon(key==='own'?'shield':'swords')}${t(th,en)}</button>`).join('')}</div>`:'';
  const metricOptions=supply?options.map(([id,th,en])=>`<option value="${id}" ${s.metric===id?'selected':''}>${t(th,en)}</option>`).join(''):`<option value="tier" ${s.metric==='tier'?'selected':''}>${t('ระดับไข่แดง · Tier 1–3','Yolk tier · Tier 1–3')}</option>${enabledMetricIds(Y.criteria).map(id=>`<option value="${id}" ${s.metric===id?'selected':''}>${esc(t(METRIC_INDEX[id].th,METRIC_INDEX[id].en))} · ${esc(t(METRIC_INDEX[id].unitTh,METRIC_INDEX[id].unitEn))}</option>`).join('')}`;
  const note=!supply?t('สีไข่ดาวบอกความเข้ม Demand ส่วนโล่และดาบบอกสาขาแต่ละฝั่ง','Egg colours show Demand; shield and swords identify the branch networks'):share?t('เรา ÷ (เรา + คู่แข่ง) × 100 · ไม่รวมแบรนด์ที่ยังไม่ทราบ ไม่ใช่ส่วนแบ่งยอดขาย','Own ÷ (own + competitors) × 100 · unknown brands excluded; not sales market share'):s.metric==='market'?t('ตัวหารตามเกณฑ์ทีม: ','Team denominator: ')+esc(t(METRIC_INDEX[Y.criteria.supplyDenominatorId]?.th||'',METRIC_INDEX[Y.criteria.supplyDenominatorId]?.en||''))+` · <a href="#criteria">${t('เปลี่ยนตัวหารในเกณฑ์','Change in criteria')}</a>`:t('สีเข้ม = สาขามากกว่าในตัววัดนี้ · ยอดต้นทางตามรูปแบบที่เลือก','Darker colour = more branches on this metric · source counts for the selected format');
  const more=supply?`<details class="analysis-advanced-metrics" ${advanced?'open':''}><summary>${icon('tune')}<span>${t('เทียบกับขนาดตลาดหรือพื้นที่','Compare with market size or land area')}</span></summary><p>${t('ตัววัดเสริมสำหรับเทียบพื้นที่ขนาดต่างกัน','Optional metrics for areas of different sizes')}</p><div class="analysis-relations">${[['market','สาขาต่อฐานตลาด','Branches per market base'],['area','สาขาต่อ ตร.กม.','Branches per km²']].map(([id,th,en])=>`<button type="button" data-analysis-extra-metric="${id}" aria-pressed="${s.metric===id}">${icon(id==='area'?'map':'tune')}${t(th,en)}</button>`).join('')}</div></details>`:'';
  return `<section class="analysis-controls" aria-labelledby="analysis-controls-title"><h2 id="analysis-controls-title">${supply?icon('store'):(global.YolkIcons?.demandIcon()||'')}${t('ดูอะไรบนแผนที่','What the map shows')}</h2><label for="analysis-metric">${t('ตัววัด','Metric')}<select id="analysis-metric" data-analysis-metric>${metricOptions}</select></label>${relations}<p>${note}</p>${more}</section>`;
 }
 function demandPage(){
  const s=views.demand,allowed=enabledMetricIds(Y.criteria);if(s.metric!=='tier'&&!allowed.includes(s.metric))s.metric='tier';
  const rows=evaluate(),prepared=global.YolkMapAnalysis?.prepare(rows,s,Y.criteria),scoped=rows.filter(inMapArea),list=(s.metric==='tier'?scoped.filter(a=>a.demand===true):scoped.filter(a=>Number.isFinite(a.metrics[s.metric]))).sort((a,b)=>s.metric==='tier'?(a.qualifyingTier||9)-(b.qualifyingTier||9)||(b.pathStrength||0)-(a.pathStrength||0)||a.id.localeCompare(b.id):(b.metrics[s.metric]-a.metrics[s.metric])||a.id.localeCompare(b.id));
  const counts=[1,2,3].map(tier=>scoped.filter(a=>a.demand===true&&a.qualifyingTier===tier).length);
  return `<div class="page-head"><div><h1>${global.YolkIcons?.demandIcon()||''}Demand · ${t('หาไข่แดง','Find the yolk')}</h1><p>${t('ตลาดเข้มข้นตรงไหน ดูสัญญาณที่ตรงกับธุรกิจของเรา','Where is the market concentrated? Explore signals relevant to your business.')}</p></div></div>${controls('demand')}<div class="analysis-tier-summary">${counts.map((n,i)=>`<div><span class="yolk-tier-label"><i class="yolk-tier-swatch" data-yolk-tier="${i+1}"></i>${global.YolkSimpleCriteria.tierLabel(i+1)}</span><strong>${num(n)}</strong><small>${t('ทำเล','locations')}</small></div>`).join('')}</div><p class="scope-note">${esc(mapNavigation().level==='country'?t('ทั้งประเทศ','Nationwide'):mapNavigationTitle())} · ${num(scoped.filter(a=>a.demand===null).length)} ${t('ทำเล Demand ยังไม่ชัด','locations with unresolved Demand')}</p><section class="analysis-results"><h2>${esc(metricLabel(s))}</h2><p>${t('เปิดทำเลเพื่อดูที่มาและเทียบสาขา','Open a location for evidence and branch comparison')}</p>${list.slice(0,20).map(a=>{const r=prepared?.records.get(a.id),saved=!!Y.targets[a.id]&&!Y.targets[a.id].archived;return `<article class="analysis-location-card"><button type="button" class="analysis-location" data-action="place" data-id="${a.id}"><span><strong>${esc(areaName(a.id))}</strong><small>${esc(provinceName(a.province))}${a.demand===true?' · Yolk':''}</small></span><span class="analysis-value"><b>${s.metric==='tier'?global.YolkSimpleCriteria.tierLabel(a.qualifyingTier):formatted(r)}</b><small>${s.metric==='tier'?t(global.YolkSimpleCriteria.tiers[a.qualifyingTier-1]?.[2]||'Demand สูง',global.YolkSimpleCriteria.tiers[a.qualifyingTier-1]?.[3]||'High Demand'):esc(unit(r))}</small></span>${icon('arrow_forward')}</button><div>${global.YolkSupplyCompare.panel(a,Y.criteria,true)}</div><div class="analysis-shortlist-action"><button type="button" class="btn ${saved?'saved':'soft'}" data-action="target" data-id="${a.id}" ${!canEdit()?'disabled':''}>${icon(saved?'bookmark_added':'bookmark_add')}${saved?t('เล็งไว้แล้ว','Shortlisted'):t('เล็งทำเลนี้','Add to shortlist')}</button></div></article>`}).join('')||`<p>${t('ยังไม่มีผลยืนยันในพื้นที่นี้','No confirmed result in this area')}</p>`}${list.length>20?`<p class="footline">${t('แสดง 20 ทำเลแรกจาก ','First 20 of ')}${num(list.length)} · ${t('เจาะพื้นที่บนแผนที่เพื่อดูเพิ่ม','Drill into the map to narrow the list')}</p>`:''}</section><p class="footline">${t('สัญญาณจากข้อมูล CityMETER ช่วยคัดพื้นที่ศึกษา ยังไม่ใช่ลูกค้าหรือยอดซื้อที่วัดจริง','CityMETER signals screen areas for investigation; they do not measure actual customers or purchases.')}</p>`;
 }
 function supplySummary(){
  if(views.supply.metric==='market'&&!global.YolkRelativeSupply?.catalog?.some(m=>m.id===Y.criteria.supplyDenominatorId))views.supply.metric='count';
  const summary=global.YolkWorkspaceMap?.supplyBreakdown?.()||{state:'loading'};
  return controls('supply')+`<div data-supply-breakdown>${global.YolkSupplyTreemap?.render(summary,{lang:Y.lang,id:'supply-panel-breakdown'})||''}</div><p class="scope-note">${t('แผนที่และกราฟใช้ยอดต้นทาง ไม่ได้รวมจากหมุด POI · รายการด้านล่างใช้ตรวจและบันทึกงานของทีม','Map and chart use source totals, not POI marker counts. The list below supports verification and team work.')}</p>`;
 }
 function updateSupplyBreakdown(summary){
  const hosts=global.document.querySelectorAll?.('[data-supply-breakdown]');if(!hosts?.length||!global.YolkSupplyTreemap)return false;
  const html=global.YolkSupplyTreemap.render(summary||{state:'loading'},{lang:Y.lang,id:'supply-panel-breakdown'});
  for(const host of hosts)host.innerHTML=html;return true;
 }
 // Native district totals require their own evidence grain; never sum display crosswalks.
 function districtRows(data){return (data?.rows||[]).map(r=>{const ctx=data.contextsById?.[r[0]]||{},counts=r[2];let supply;
  if(Y.industry!=='nonbank')supply=calculateSupply(r,{province:ctx.provinceCode,nativeDistrict:true});
  else if(r[1]!=='source_row_present'||!counts)supply={own:null,competitor:null,unverified:null,state:'missing'};
  else {let own=0,competitor=0,review=0;const key=rawOwnId();for(const [id,n]of Object.entries(counts)){if(!Number.isInteger(n)||n<0){review=NaN;break;}if(id===key)own+=n;else {const member=selectedScopeIncludes(id);if(member===true)competitor+=n;else if(member===null)review+=n;}}const residual=data.assignmentBoundsById?.[r[0]]||{};let ownResidual=residual[key]||0,otherResidual=0;for(const [id,n]of Object.entries(residual))if(id!==key&&selectedScopeIncludes(id)!==false)otherResidual+=n;
   supply=Number.isFinite(review)?{own,competitor,unverified:0,ownLower:own,ownUpper:own+ownResidual,competitorLower:competitor,competitorUpper:competitor+review+otherResidual,state:'native_district_inventory',sourceKey:r[4],unknownLicense:review}:{own:null,competitor:null,unverified:null,state:'invalid'};
  }
  if(ownScopeAvailable()!==true){supply.own=null;supply.ownScopeUnavailable=true;delete supply.ownLower;delete supply.ownUpper;}
  return {id:r[0],province:ctx.provinceCode,th:ctx.name,areaKm2:ctx.areaKm2,metricStates:ctx.metricStates,metrics:{population:ctx.population??null,gfa:ctx.gfa??null,adult_population_20_64:ctx.adult_population_20_64??null,working_age_15_64:ctx.working_age_15_64??null,...ctx.metrics},supply,sourceMetadata:data.metadata};
 });}
 global.YolkAnalysisUI=Object.freeze({state,set,controls,demandPage,supplySummary,updateSupplyBreakdown,districtRows,formatted,unit,metricLabel});
 global.document.addEventListener('change',event=>{if(!event.target.matches('[data-analysis-metric]'))return;if(set('metric',event.target.value)){render();}});
 global.document.addEventListener('click',event=>{const extra=event.target.closest('[data-analysis-extra-metric]');if(extra?.dataset.analysisExtraMetric){if(set('metric',extra.dataset.analysisExtraMetric))render();return;}const b=event.target.closest('[data-analysis-relation]');if(!b)return;if(set('relation',b.dataset.analysisRelation)){Y.poiTab=b.dataset.analysisRelation==='total'?'all':b.dataset.analysisRelation;Y.page=0;render();}});
})(window);
