/* Public, versioned adapters are loaded before the preserved original v1.5 UI. */
(async function(root){
  const content=document.getElementById('content');
  content.innerHTML='<section class="section"><h1>CityMETER: Yolk</h1><p role="status">กำลังอ่านข้อมูลพื้นที่จริง 7,954 หน่วย · Loading the observed area-context snapshot.</p></section>';
  const get=async file=>{const response=await fetch('data/real/'+file,{cache:'no-store'});if(!response.ok)throw new Error(file+' HTTP '+response.status);return response.json()};
  try{
    let requestedIndustry='fuel';try{const saved=JSON.parse(localStorage.getItem('citymeter-yolk-three-industries-workspace-v1')||'{}');if(['fuel','grocery','nonbank'].includes(saved.industry))requestedIndustry=saved.industry}catch{}
    const [context,fuel,profiles,assetHashes]=await Promise.all([get('area-context.json'),get(requestedIndustry+'-supply.json'),fetch('contracts/industry-profiles.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('Profile unavailable');return r.json()}),fetch('contracts/runtime-asset-hashes.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('Asset manifest unavailable');return r.json()})]);
    if(context.rows.length!==7954||context.metrics.length!==25||context.metrics.some(m=>!m.display))throw new Error('Snapshot catalogue or display copy unavailable');
    const metrics=context.metrics,areas=context.rows.map((r,index)=>({id:r[0],th:r[1],en:r[1],province:r[2],geoType:r[3]==='SUBDISTRICT'?'khwaeng':'local_authority',areaKm2:r[4],bbox:r[5],extent3857:r[6],areaCode:r[7],geometryStatus:'source_extent_only',sourceRank:index,metrics:Object.fromEntries(metrics.map((m,i)=>[m.id,r[8][i]])),metricStates:Object.fromEntries(metrics.map((m,i)=>[m.id,{state:context.stateCatalog[r[9][i]],measurement:m.measurement,sourceMetricId:m.sourceMetricId}])),population:r[8][metrics.findIndex(m=>m.id==='population')],supply:{own:null,competitor:null,unverified:null},mapContext:{boundaryStatus:'missing',extent3857:r[6],extentStatus:'source_extent_only',pois:[]}}));
    root.YOLK_RUNTIME={metadata:context.metadata,metricCatalog:metrics,profiles:profiles.profiles||profiles,supplyCache:new Map([[requestedIndustry,fuel]]),pointCache:new Map(),companyScopes:null,revision:0};
    if(requestedIndustry==='nonbank'){const [scopes,bounds]=await Promise.all([get('nonbank-company-scopes.json'),get('nonbank-assignment-bounds.json')]);root.YOLK_RUNTIME.companyScopes=scopes;root.YOLK_RUNTIME.assignmentBounds=bounds;}
    root.YOLK_DEMO_DATA={metadata:{...context.metadata,thresholds:{},poiSampleAreaIds:[areas[0].id]},areas,pois:[]};
    const files=['icons.js','metrics.js','model.js','industry-workspace.js','landscape.js','leaderboard.js','supply-ui.js','vendor/leaflet-1.9.4/leaflet.js','location-map.js','branch-photos.js','decision-ui.js','app.js'];
    for(const file of files)await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=file+'?v='+assetHashes[file];script.onload=resolve;script.onerror=()=>reject(new Error(file+' failed'));document.body.append(script)});
  }catch(error){content.innerHTML='<section class="section"><h1>อ่านข้อมูลไม่สำเร็จ · Data unavailable</h1><p>เปิดต้นแบบผ่าน static server แล้วลองโหลดใหม่ · Serve the prototype through a local static server and reload.</p><p role="alert">'+String(error.message).replace(/[<>&]/g,'')+'</p><button class="btn" onclick="location.reload()">โหลดใหม่ · Reload</button></section>';}
})(window);
