/* Known context seeds drafts; display polygons never certify source membership or operations. */
(function (global) {
 'use strict';
 const forms=new WeakMap(),bounds=new WeakMap();
 const trText=(th,en)=>typeof tr==='function'?tr(th,en):th;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function coordinatePair(lat,lng){if([lat,lng].some(v=>v===null||v===undefined||String(v).trim()===''))return null;const p={lat:Number(lat),lng:Number(lng)};return Number.isFinite(p.lat)&&Number.isFinite(p.lng)&&Math.abs(p.lat)<=90&&Math.abs(p.lng)<=180?p:null;}
 function classifyPoint(feature,p){
  const g=feature?.geometry;if(!p||typeof p.lat!=='number'||typeof p.lng!=='number'||!coordinatePair(p.lat,p.lng)||!['Polygon','MultiPolygon'].includes(g?.type))return 'invalid';
  let cached=bounds.get(g);if(!cached){const polygons=g.type==='Polygon'?[g.coordinates]:g.coordinates;const box=[Infinity,Infinity,-Infinity,-Infinity];if(!Array.isArray(polygons)||!polygons.length)return 'invalid';let valid=true;for(const poly of polygons||[]){if(!Array.isArray(poly)||!poly.length){valid=false;break;}for(const ring of poly){if(!Array.isArray(ring)||ring.length<4){valid=false;break;}for(const xy of ring){if(!Array.isArray(xy)||!Number.isFinite(xy[0])||!Number.isFinite(xy[1])){valid=false;break;}box[0]=Math.min(box[0],xy[0]);box[1]=Math.min(box[1],xy[1]);box[2]=Math.max(box[2],xy[0]);box[3]=Math.max(box[3],xy[1]);}}}cached={valid,box,polygons};bounds.set(g,cached);}if(!cached.valid)return 'invalid';
  const e=1e-10,[west,south,east,north]=cached.box;if(p.lng<west-e||p.lng>east+e||p.lat<south-e||p.lat>north+e)return 'outside';
  const ringState=ring=>{let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [x,y]=ring[i],[a,b]=ring[j],dx=x-a,dy=y-b,length=Math.hypot(dx,dy);if(length>0&&Math.abs((p.lng-a)*dy-(p.lat-b)*dx)<=e*length&&p.lng>=Math.min(a,x)-e&&p.lng<=Math.max(a,x)+e&&p.lat>=Math.min(b,y)-e&&p.lat<=Math.max(b,y)+e)return 'boundary';if((y>p.lat)!==(b>p.lat)&&p.lng<(a-x)*(p.lat-y)/(b-y)+x)inside=!inside;}return inside?'inside':'outside';};
  let interior=false;for(const poly of cached.polygons){const outer=ringState(poly[0]);if(outer==='boundary')return 'boundary';if(outer!=='inside')continue;let hole=false;for(const ring of poly.slice(1)){const state=ringState(ring);if(state==='boundary')return 'boundary';if(state==='inside')hole=true;}if(!hole)interior=true;}return interior?'inside':'outside';
 }
 function brands(){return (global.YOLK_RUNTIME.supplyCache.get(Y.industry)?.brands||[]).map(b=>({...b}));}
 const normalized=v=>String(v??'').normalize('NFKC').toLocaleLowerCase().replace(/\s+/g,'').trim();
 function canonicalBrand(value,existingBrandId){const list=brands(),key=normalized(value);if(!key)return list.find(b=>b.id===existingBrandId)||null;const matches=list.filter(b=>{const r=global.YolkBrands?.record(b.id);return [b.id,b.name,r?.name?.th,r?.name?.en,...(r?.aliases||[]),...(b.id==='ptt'?['ปตท.']:[])].some(v=>normalized(typeof v==='string'?v:'')===key);});return matches.length===1?matches[0]:null;}
 function initialValues(existing,nav=global.YolkWorkspaceMap?.getNavigation?.()||{level:'country'}){
  if(existing){const p={...existing};p.province=AREA_INDEX.get(p.area)?.province||p.province||p.adminScope?.province_code||'';return p;}
  const areaId=nav.level==='location'&&AREA_INDEX.has(nav.areaId)?nav.areaId:(Y.poiArea&&AREA_INDEX.has(Y.poiArea)?Y.poiArea:''),a=AREA_INDEX.get(areaId);const brand=canonicalBrand(Y.brandFilter)|| (Y.poiTab==='own'?brands().find(b=>b.id===Y.ownBrandId):null);
  return {id:'new',name:'',brand:brand?.name||'',brandId:brand?.id||null,relation:brand?pointRelation({brandId:brand.id}):'unverified',province:a?.province||nav.provinceCode||'',area:areaId,status:'pending',lat:'',lng:'',note:'',revision:0};
 }
 function photoDraftId(p){return p.id==='new'?'new:'+criteriaContextKey():p.id;}
 function stateSnapshot(form){const s=forms.get(form);return s?{manualProvince:s.manualProvince,manualArea:s.manualArea,autoProvince:s.autoProvince,autoArea:s.autoArea,candidates:s.candidates,result:s.result,resultPoint:s.resultPoint}:null;}
 function restore(form,s){if(s)forms.set(form,{...s,generation:0,timer:null});}
 function rebuild(form,s,all=false){const province=form.elements.province.value,area=form.elements.area.value;let candidates=s.candidates?.filter(c=>c.province===province)||[];const nav=global.YolkWorkspaceMap?.getNavigation?.();const ids=!all&&candidates.length?candidates.map(c=>c.id):!all&&nav?.level==='district'&&nav.provinceCode===province?global.YolkWorkspaceMap.areaIdsForDistrict(nav.districtId):null;form.elements.area.innerHTML=areaOptions(province,area,ids);form.querySelector('label[for="branch-area"]').textContent=province==='10'?trText('แขวง','Khwaeng'):trText('อปท. / ทำเล','Local authority / location');}
 function message(form,s,result){const box=form.querySelector('#branch-context-note');if(!box)return;const unique=result.areaCandidates.length===1&&result.areaCandidates[0].classification==='inside';const c=unique?result.areaCandidates[0]:null,conflict=c&&(form.elements.area.value!==c.id||form.elements.province.value!==c.province);let text=unique?trText('พบพื้นที่จากพิกัด: ','Coordinate match: ')+areaName(c.id)+' · '+provinceName(c.province):result.areaCandidates.length?trText('พิกัดอยู่ใกล้เส้นแบ่งหรือพื้นที่ซ้อนกัน เลือกพื้นที่ที่ตรวจแล้วจากรายการ','Boundary or overlapping matches. Choose a checked area from the list.'):result.provinceCandidates.length?trText('พบจังหวัดจากพิกัด แต่ยังระบุทำเลไม่ได้ เลือกจากรายการหรือบันทึกไว้ตรวจต่อ','Province found; fine area unresolved. Choose an area or save for later review.'):trText('ยังหาพื้นที่จากพิกัดไม่ได้ บันทึกโน้ตและรูปไว้ตรวจต่อได้','Area unresolved. You can save notes and photos for later review.');box.innerHTML=`<p>${esc(text)}</p>${conflict?`<button class="btn secondary" type="button" data-branch-context="apply">${trText('ใช้พื้นที่ตามพิกัด','Use coordinate match')}</button>`:''}<button class="btn secondary" type="button" data-branch-context="all">${trText('ดูทำเลทั้งหมดในจังหวัด','Show all areas in province')}</button><small>${trText('อ้างอิงขอบเขตแผนที่ต้นทาง ไม่ได้ยืนยันเขตทางกฎหมายหรือการเปิดสาขา','Source display boundary; does not certify legal membership or branch operation.')}</small>`;global.YolkIcons?.captionControls(box);}
 function apply(form,s,result,explicit=false){const unique=key=>result[key].length===1&&result[key][0].classification==='inside';const a=unique('areaCandidates')?result.areaCandidates[0]:null,p=unique('provinceCandidates')?result.provinceCandidates[0]:null;
  if(!explicit&&s.autoArea&&!a)form.elements.area.value='';if(!explicit&&s.autoProvince&&!p)form.elements.province.value='';
  if((explicit||!s.manualProvince)&&p&&(!form.elements.province.value||s.autoProvince||explicit)){form.elements.province.value=p.code;s.autoProvince=!explicit;}
  s.candidates=result.areaCandidates;const prior=form.elements.area.value;rebuild(form,s);if(prior&&!form.elements.area.value){form.elements.area.innerHTML=areaOptions(form.elements.province.value,prior);form.elements.area.value=prior;}
  if(a&&(explicit||!s.manualArea)&&(!form.elements.area.value||s.autoArea||explicit)&&form.elements.province.value===a.province){form.elements.area.innerHTML=areaOptions(a.province,a.id,s.candidates.map(c=>c.id));form.elements.area.value=a.id;s.autoArea=!explicit;}
  if(explicit){s.manualArea=true;s.manualProvince=true;s.autoArea=false;s.autoProvince=false;}s.result=result;s.resultPoint=coordinatePair(form.elements.lat.value,form.elements.lng.value);message(form,s,result);if(a&&form.elements.area.value===a.id)global.YolkWorkspaceMap?.previewBranchArea?.(a.id);}
 function invalidate(form,s){if(s.autoArea){form.elements.area.value='';global.YolkWorkspaceMap?.clearBranchArea?.();}if(s.autoProvince)form.elements.province.value='';s.result=null;s.resultPoint=null;s.candidates=[];rebuild(form,s,true);}
 function bind(form=document.getElementById('poi-form')){if(!form||form.dataset.contextBound)return;form.dataset.contextBound='true';const p=Y.pois.find(p=>p.id===form.dataset.id),fresh=!p;const s=forms.get(form)||{manualProvince:!!p?.province||!!p?.area,manualArea:!!p?.area,autoProvince:fresh,autoArea:fresh,generation:0,timer:null,candidates:[],result:null};forms.set(form,s);rebuild(form,s);if(s.result)message(form,s,s.result);
  const lookup=async()=>{const coords=coordinatePair(form.elements.lat.value,form.elements.lng.value);if(!coords){if(s.result){invalidate(form,s);const note=form.querySelector('#branch-context-note');if(note)note.textContent=trText('กรอกพิกัดทั้งคู่ให้ถูกต้อง หรือเลือกพื้นที่เอง ข้อมูลที่แก้เองยังคงอยู่','Enter a valid coordinate pair or choose an area. Manual choices are retained.');}return;}const signature=JSON.stringify(coords),generation=++s.generation,key=criteriaContextKey(),route=location.hash,revision=form.dataset.revision;const box=form.querySelector('#branch-context-note');if(box)box.textContent=trText('กำลังเทียบพิกัดกับพื้นที่…','Matching coordinates to areas…');try{const result=await global.YolkWorkspaceMap.resolvePoint(coords);if(!form.isConnected||key!==criteriaContextKey()||route!==location.hash||generation!==s.generation||revision!==form.dataset.revision||signature!==JSON.stringify(coordinatePair(form.elements.lat.value,form.elements.lng.value)))return;apply(form,s,result);}catch{if(form.isConnected&&key===criteriaContextKey()&&route===location.hash&&generation===s.generation&&revision===form.dataset.revision&&signature===JSON.stringify(coordinatePair(form.elements.lat.value,form.elements.lng.value))&&box){invalidate(form,s);box.textContent=trText('โหลดขอบเขตไม่ได้ เลือกจังหวัดเพื่อจำกัดรายการ หรือบันทึกไว้ตรวจต่อ','Boundaries unavailable. Select a province to narrow choices, or save for later review.');}}};
  form.addEventListener('input',e=>{if(e.target.name==='brand'){const b=canonicalBrand(e.target.value);if(b)form.elements.relation.value=pointRelation({brandId:b.id});}if(['lat','lng'].includes(e.target.name)){++s.generation;invalidate(form,s);const note=form.querySelector('#branch-context-note');if(note)note.textContent=trText('กำลังเทียบพิกัดใหม่ ข้อมูลที่เลือกเองยังคงอยู่','Matching the new coordinates. Manual choices are retained.');clearTimeout(s.timer);s.timer=setTimeout(lookup,250);}});
  form.addEventListener('change',e=>{const name=e.target.name;if(name==='province'){++s.generation;s.manualProvince=true;s.autoProvince=false;const a=AREA_INDEX.get(form.elements.area.value);if(a?.province!==e.target.value)form.elements.area.value='';rebuild(form,s,true);if(s.result)message(form,s,s.result);}else if(name==='area'){++s.generation;s.manualArea=true;s.autoArea=false;const a=AREA_INDEX.get(e.target.value);if(a){form.elements.province.value=a.province;s.manualProvince=true;s.autoProvince=false;global.YolkWorkspaceMap?.previewBranchArea?.(a.id);}if(s.result)message(form,s,s.result);}else if(name==='brand'){const b=canonicalBrand(e.target.value);if(b){e.target.value=b.name;form.elements.relation.value=pointRelation({brandId:b.id});}}else if(name==='relation'&&e.target.value==='own'){const b=brands().find(b=>b.id===Y.ownBrandId);if(b)form.elements.brand.value=b.name;}});
  form.addEventListener('click',e=>{const b=e.target.closest('[data-branch-context]');if(!b)return;if(b.dataset.branchContext==='all')rebuild(form,s,true);else if(s.result)apply(form,s,s.result,true);});lookup();}
 function assignment(form){const s=forms.get(form);if(JSON.stringify(s?.resultPoint)!==JSON.stringify(coordinatePair(form.elements.lat.value,form.elements.lng.value)))return null;const a=s?.result?.areaCandidates.find(c=>c.id===form.elements.area.value);return a?{method:s.manualArea?'team_choice_after_coordinate_hint':'coordinate_display_polygon',classification:a.classification,sourceFiles:s.result.sourceFiles,legalBoundaryIndependentlyVerified:false}:null;}
 global.YolkBranchContext=Object.freeze({coordinatePair,classifyPoint,brands,canonicalBrand,initialValues,photoDraftId,bind,snapshot:stateSnapshot,restore,assignment});
})(window);
