/* Evidence review explains model uncertainty; it never approves a POI or rewrites source totals. */
(function(global){
 'use strict';
 const t=(th,en)=>Y.lang==='en'?en:th,esc=value=>escapeHTML(value),icon=name=>global.YolkIcons?.icon(name)||'';
 function report(row,c=Y.criteria){
  const sp=row.supply||{},thresholds=row.supplyThresholds||supplyThresholds(row,c),possible=[...new Set(row.possiblePatterns||[])];
  const reasons=[],missing=enabledMetricIds(c).filter(id=>!Number.isFinite(row.metrics?.[id]));
  if(row.demand===null)reasons.push({id:'demand_missing',th:'สัญญาณ Demand ยังไม่ครบ',en:'Demand evidence is incomplete',actionTh:'เติมข้อมูลของตัววัดที่ขาดในขอบเขตทำเลเดิม แล้วคำนวณใหม่ ไม่แทนค่าที่หายด้วยศูนย์',actionEn:'Obtain missing selected metrics for this reporting boundary, then recalculate. Do not substitute zero.'});
  if(!thresholds.valid)reasons.push({id:'market_base_missing',th:'ฐานตลาดที่ใช้หารยังไม่พร้อม',en:'Market denominator is unavailable',actionTh:'ตรวจค่าฐานตลาดและหน่วยให้ตรง UUID ทำเล ต้องเป็นค่าจริงใน snapshot ที่มากกว่าศูนย์ หรือเลือกฐานอื่นที่มีข้อมูลและตรงกับธุรกิจ',actionEn:'Check a positive source denominator, unit and exact reporting UUID, or explicitly choose an available, relevant denominator.'});
  const ambiguous=possible.length>1;
  if(Number.isFinite(sp.unverified)&&sp.unverified>0)reasons.push({id:'brand_allocation',th:'ต้นทางยังไม่ระบุแบรนด์บางสาขา',en:'Some source branches have no identified brand',actionTh:'ตรวจว่าแต่ละรายการเป็นสาขาเรา คู่แข่ง หรือยังไม่ทราบ จากข้อมูลแบรนด์และพิกัด แล้วกระทบยอดรายการกับยอดรวมในทำเล',actionEn:'Identify each unresolved record as own, competitor or unknown using brand and location evidence, then reconcile records to the area aggregate.'});
  if(sp.state==='source_inventory_with_assignment_bounds'&&(sp.ownUpper>sp.ownLower||sp.competitorUpper>sp.competitorLower))reasons.push({id:'area_assignment',th:'สำนักงานบางรายการยังไม่ผูกกับทำเล',en:'Some offices lack a reporting-area assignment',actionTh:'ผูกแต่ละสำนักงานเข้าขอบเขตทำเลด้วยพิกัดและ crosswalk ที่ตรวจแล้ว จากนั้นกระทบยอดระดับทำเลและจังหวัด โดยไม่กระจายยอดคงเหลือซ้ำทุกทำเล',actionEn:'Assign each office using coordinates and a checked reporting-boundary crosswalk, then reconcile area and province totals without duplicating residuals.'});
  if(sp.unknownLicense>0)reasons.push({id:'license_scope',th:'ขอบเขตใบอนุญาตของบางบริษัทยังไม่ชัด',en:'Some company-license scopes are unresolved',actionTh:'ตรวจนิติบุคคลและสถานะใบอนุญาตกับแหล่งทางการ พร้อมวันที่อ้างอิง ข้อมูลใบอนุญาตบริษัทไม่ยืนยันบริการจริงของทุกสาขา',actionEn:'Check legal identity and dated official license status. A company license does not confirm products at every branch.'});
  if(sp.reconciliationReview)reasons.push({id:'source_reconciliation',th:'ยอดรวมและหมวดร้านในต้นทางยังไม่ตรงกัน',en:'Source totals and store categories do not reconcile',actionTh:'ให้ต้นทางยืนยันรายการและหมวดร้านที่ต่างกัน แล้วแก้ยอดใน UUID ที่ถูกต้อง ไม่บวกหรือลบหนึ่งสาขาซ้ำทุกทำเล',actionEn:'Resolve the discrepant records and categories with the source and correct their exact UUIDs; do not adjust every area by one.'});
  if(thresholds.valid&&!validSupply(sp)&&!validSupplyBounds(sp))reasons.push({id:'supply_missing',th:'ยอด Supply ในขอบเขตที่เลือกยังไม่ครบ',en:'Supply totals in the selected scope are incomplete',actionTh:'ตรวจขอบเขตแบรนด์/format และยอดรวมที่ต้นทางรายงานก่อนสรุป มากหรือน้อย',actionEn:'Check brand/format scope and complete reported source totals before classifying high or low.'});
  const roles=['own','competitor'].map(role=>{let lo=validSupplyBounds(sp)?sp[role+'Lower']:sp[role],hi=validSupplyBounds(sp)?sp[role+'Upper']:Number.isFinite(sp[role])&&Number.isFinite(sp.unverified)?sp[role]+sp.unverified:null,threshold=thresholds[role];const state=!thresholds.valid||!Number.isFinite(lo)||!Number.isFinite(hi)?'unknown':lo>=threshold?'high':hi<threshold?'low':'crosses';return {role,lo,hi,threshold,state};});
  return {id:row.id,reasons,missing,roles,possible,patternConfirmed:possible.length===1,demand:row.demand,qualifyingTier:row.qualifyingTier,eligible:!!row.eligible,strategyReview:!!row.reviewCandidate,classificationUnresolved:ambiguous,sourceState:sp.state,criteriaVersion:c.version};
 }
 function rolesView(r){return `<dl class="review-role-evidence">${r.roles.map(role=>`<div><dt>${esc(role.role==='own'?ownBrandName():t('คู่แข่ง','Competitors'))}</dt><dd>${Number.isFinite(role.lo)&&Number.isFinite(role.hi)?num(role.lo)+(role.lo!==role.hi?'–'+num(role.hi):''):'—'} ${t('สาขา','branches')}</dd><small>${Number.isFinite(role.threshold)?t('เริ่มมากที่ ','High from ')+num(role.threshold,2)+' '+t('สาขา','branches'):t('ยังคำนวณเกณฑ์จำนวนไม่ได้','Count threshold unavailable')} · ${role.state==='crosses'?t('ช่วงคร่อมเกณฑ์ จึงยังแยกมาก/น้อยไม่ได้','Interval crosses threshold; high/low unresolved'):role.state==='high'?t('มาก','High'):role.state==='low'?t('น้อย','Low'):t('รอข้อมูล','Unresolved')}</small></div>`).join('')}</dl>`;}
 function body(row,c=Y.criteria){const r=report(row,c);return `<div class="review-context"><strong>${esc(areaName(row.id))}</strong><small>${esc(provinceName(row.province))} · ${t('เกณฑ์','Criteria')} v${c.version}</small></div><p>${YolkDecisions.tierText(row)} · ${r.demand===true?t('Demand ผ่านเกณฑ์ ส่วน Supply ใช้เปรียบเทียบและจัดอันดับ','Demand qualifies. Supply supports comparison and ranking.'):t('ตรวจสัญญาณ Demand ก่อนคัดทำเล','Check Demand evidence before screening this place.')}</p>${global.YolkSupplyCompare?.panel(row,c)||''}${r.reasons.length?`<ol class="review-reasons">${r.reasons.map(reason=>`<li><strong>${icon('fact_check')}${esc(t(reason.th,reason.en))}</strong><p>${esc(t(reason.actionTh,reason.actionEn))}</p></li>`).join('')}</ol>`:`<p class="review-result-note">${t('สัญญาณที่ใช้มีข้อมูลพอคำนวณแล้ว ไม่ต้องกดอนุมัติทำเล','The selected signals can be calculated. No location approval click is needed.')}</p>`}${r.demand===null&&r.missing.length?`<p><b>${t('ตัววัดที่ขาด','Missing metrics')}</b><br>${r.missing.map(id=>esc(t(METRIC_INDEX[id]?.th||id,METRIC_INDEX[id]?.en||id))).join(' · ')}</p>`:''}<p>${t('ข้อมูล Supply ที่ยังไม่แน่ไม่ตัดทำเลออกจากกลุ่ม Demand แต่คะแนนจัดอันดับอาจเป็นช่วง ต้องตรวจหลักฐานก่อนตัดสินใจลงทุน','Uncertain Supply does not remove a Demand-qualified place; ranking may be an interval. Check the evidence before investing.')}</p><a class="btn" href="https://landometer.com/v3/citymeter?d=${CITYMETER_DATASETS[Y.industry]}" target="_blank" rel="noopener">${icon('open_in_new')}${t('เทียบข้อมูลต้นทาง CityMETER','Compare CityMETER source')}</a><p class="footline">${t('การคำนวณนี้ไม่ยืนยันการเปิดบริการจริง การแก้ POI เป็นบันทึกของทีม ยอดรวมเปลี่ยนหลังตรวจ crosswalk และกระทบยอดใน production','This calculation does not verify current operations. POI edits are team evidence; aggregates change after a reconciled production crosswalk.')}</p>`;}
 function open({areaId,pattern,page=0}={}){
  let dialog=document.getElementById('location-review-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='location-review-dialog';dialog.className='location-review-dialog';document.body.append(dialog);}
  const c=Y.route==='criteria'?draft:Y.criteria;if(criteriaErrors({...c,patterns:patternNames}).length)return;
  const rows=evaluate(c);
  const row=areaId?rows.find(a=>a.id===areaId):null;
  const selected=rows.filter(a=>a.demand!==null&&(a.demand===false?c.demandMode==='all':a.tierEligible)&&a.possiblePatterns.length>1&&(!pattern||a.possiblePatterns.includes(pattern)));
  page=Math.max(0,Math.min(page,Math.ceil(selected.length/40)-1));
  dialog.innerHTML=`<div class="review-dialog-head"><h2 id="review-dialog-title">${icon('fact_check')}${t('รอตรวจอะไร?','What needs checking?')}</h2><button type="button" class="btn" data-review-close aria-label="${t('ปิด','Close')}">${icon('close')}</button></div>${row?body(row,c):`<p>${t('หมายถึงข้อมูลยังสรุปรูปแบบทำเลไม่ได้ ไม่ใช่งานรออนุมัติ และไม่ใช่สถานะยืนยันว่าสาขาเปิดบริการ','This means the location pattern is unresolved. It is not an approval queue or branch-operation verification.')}</p><p><strong>${pattern?esc(pattern)+' · ':''}${num(selected.length)} ${t('ทำเล','locations')}</strong> · ${t('ทำเลเดียวอาจปรากฏหลายรูปแบบ จึงไม่ควรบวกรวมจำนวนรอตรวจในการ์ด','One location may appear under several types; do not sum card review counts.')}</p><div class="review-location-list">${selected.slice(page*40,(page+1)*40).map(a=>{const r=report(a,c);return `<button type="button" data-review-detail="${a.id}"><span><strong>${esc(areaName(a.id))}</strong><small>${esc(provinceName(a.province))} · ${r.reasons.map(x=>esc(t(x.th,x.en))).join(' / ')||t('ตรวจช่วง Supply','Check Supply bounds')}</small></span>${icon('arrow_forward')}</button>`}).join('')||`<p>${t('ไม่มีทำเลที่รอยืนยันรูปแบบในเงื่อนไขนี้','No unresolved patterns under these settings.')}</p>`}</div>${selected.length>40?`<div class="review-pagination"><button type="button" class="btn" data-review-page="${page-1}" data-review-pattern="${esc(pattern||'')}" ${page===0?'disabled':''}>${t('ก่อนหน้า','Previous')}</button><span>${num(page*40+1)}–${num(Math.min((page+1)*40,selected.length))} / ${num(selected.length)}</span><button type="button" class="btn" data-review-page="${page+1}" data-review-pattern="${esc(pattern||'')}" ${(page+1)*40>=selected.length?'disabled':''}>${t('ถัดไป','Next')}</button></div>`:''}<p>${t('Demand ที่ยังไม่ครบแยกไว้ในหน้า Demand และไม่ถูกนับว่าเป็นไข่แดง','Incomplete Demand is shown separately under Demand and is not counted as high-demand Yolk.')}</p><a href="https://github.com/montri-th/yolk/blob/main/docs/LOCATION_REVIEW_v1.7.3.md" target="_blank" rel="noopener">${t('อ่านขั้นตอนตรวจและผลที่ตรวจแล้ว','Read the checklist and audit findings')}</a>`}${row?`<button type="button" class="btn primary" data-review-place="${row.id}">${icon('location_on')}${t('เปิดรายละเอียดทำเล','Open location detail')}</button>`:''}`;
  global.YolkIcons?.captionControls?.(dialog);dialog.setAttribute('aria-labelledby','review-dialog-title');if(!dialog.open)dialog.showModal();else dialog.scrollTop=0;
 }
 function detail(row){const r=report(row);return `<section class="section location-review-summary"><h2>${icon('fact_check')}${t('หลักฐานและสิ่งที่ควรตรวจ','Evidence and next checks')}</h2><p>${r.demand===null?t('Demand ยังไม่ครบ ต้องเติมข้อมูลก่อนคัดเป็นไข่แดง','Demand is incomplete; obtain evidence before classifying a Yolk.'):r.reasons.length?t('Demand คัดได้แล้ว แต่มีข้อมูล Supply ที่ควรตรวจเพิ่ม','Demand can be screened; some Supply evidence needs checking.'):t('ข้อมูลที่ใช้คำนวณพร้อมแล้ว ยังควรสำรวจหน้าร้านและการเข้าถึงจริง','The selected data is usable. Still verify the actual site and access.')}</p><button type="button" class="btn" data-location-review="${row.id}">${icon('fact_check')}${t('ดูหลักฐานและขั้นตอนตรวจ','View evidence and checks')}</button></section>`;}
 document.addEventListener('click',event=>{const button=event.target.closest('[data-location-review],[data-pattern-review-open],[data-review-close],[data-review-detail],[data-review-place],[data-review-page]');if(!button)return;event.preventDefault();event.stopPropagation();if(button.hasAttribute('data-review-page'))open({pattern:button.dataset.reviewPattern,page:Number(button.dataset.reviewPage)});else if(button.hasAttribute('data-review-close'))document.getElementById('location-review-dialog')?.close();else if(button.dataset.reviewPlace){document.getElementById('location-review-dialog')?.close();Y.selected=button.dataset.reviewPlace;location.hash='place/'+Y.selected;}else open({areaId:button.dataset.locationReview||button.dataset.reviewDetail,pattern:button.dataset.patternReviewOpen});});
 global.YolkLocationReview={report,body,detail,open};
})(window);
