/* Read-only, illustrated strategy guide; never edits screening or team state. */
(function(global){
 'use strict';
 let registry=null,pending=null,ticket=0,opener=null;
 const t=(th,en)=>tr(th,en),e=v=>escapeHTML(String(v??'')),copy=v=>typeof v==='string'?v:(Y.lang==='th'?v?.th:v?.en)||v?.th||'',icon=n=>global.YolkIcons.icon(n);
 function load(){if(registry)return Promise.resolve(registry);if(!pending)pending=fetch('data/strategy-guide.v1.9.3.json?v=1.9.3').then(r=>{if(!r.ok)throw new Error('Guide unavailable');return r.json();}).then(r=>{if(!Array.isArray(r.strategies)||r.strategies.length!==8)throw new Error('Incomplete guide');registry=r;return r;}).catch(err=>{pending=null;throw err;});return pending;}
 function dialog(){let d=document.getElementById('strategy-guide-dialog');if(d)return d;d=document.createElement('dialog');d.id='strategy-guide-dialog';d.className='strategy-guide-dialog';d.setAttribute('aria-labelledby','strategy-guide-title');document.body.appendChild(d);d.addEventListener('close',()=>{ticket++;opener?.isConnected&&opener.focus({preventScroll:true});});d.addEventListener('click',ev=>{if(ev.target===d)d.close();});return d;}
 function chrome(content){return `<div class="strategy-guide-toolbar"><button class="btn" data-guide-index>${icon('layers')}${t('8 วิธีขยาย','8 approaches')}</button><button class="btn guide-close" data-guide-close aria-label="${t('ปิดคู่มือ','Close guide')}">${icon('close')}</button></div>${content}`;}
 function index(){return `<header class="strategy-guide-header"><h2 id="strategy-guide-title">${t('รู้จัก 8 Strategy','Meet the 8 strategies')}</h2><p>${t('มองหาลูกค้า ดูการแข่งขัน แล้วเลือกวิธีที่เข้ากับแบรนด์ แตะไอคอนเพื่อดูภาพและตัวอย่าง','Find demand, compare competition, and choose your approach. Tap an icon for illustrations and examples.')}</p></header><div class="strategy-guide-index">${registry.strategies.map((s,i)=>`<button class="strategy-guide-tile" data-guide-id="${e(s.id)}">${icon(s.icon)}<span class="guide-number">${String(i+1).padStart(2,'0')}</span><strong>${e(copy(s.shortLabel||s.name))}</strong><span>${e(copy(s.oneSentence))}</span></button>`).join('')}</div><p class="guide-disclaimer">${t('ตัวอย่างเป็นสถานการณ์สมมติ ต้องตรวจข้อมูลและหน้างานก่อนเปิดสาขา','Examples are hypothetical. Validate evidence and the site before opening.')}</p>`;}
 const labels={own:['สาขาเรา','Our store'],competitor:['คู่แข่ง','Competitor'],candidate:['ทำเลที่เล็ง','Candidate'],anchor:['จุดดึงคน','Anchor'],future:['ตลาดอนาคต','Future market']};
 function diagram(s){
  const configurations={
   underserved_market:[['own',65,145],['candidate',250,130]],
   segment_gap:[['competitor',115,130],['competitor',210,75],['candidate',275,165]],
   competitive_entry:[['competitor',110,90],['competitor',205,165],['candidate',275,100]],
   cluster_participation:[['competitor',155,100],['competitor',215,150],['candidate',245,85]],
   complementary_location:[['anchor',145,105],['candidate',255,145]],
   route_capture:[['own',70,175],['candidate',245,115]],
   network_infill:[['own',100,90],['own',305,160],['candidate',205,125]],
   future_entry:[['own',65,175],['future',235,115],['candidate',305,165]]
  },points=configurations[s.id]||[],g={own:'shield',competitor:'swords',candidate:'location_on',anchor:'store',future:'flag'};
  return `<figure class="strategy-story"><div class="strategy-story-scene" role="img" aria-label="${e(copy(s.oneSentence))}"><svg viewBox="0 0 400 240" aria-hidden="true"><path class="guide-road" d="M0 185 C100 165 175 90 400 125"/><ellipse class="guide-demand" cx="220" cy="115" rx="135" ry="82"/><path class="guide-arrow" d="M170 180 Q210 215 270 185"/></svg><span class="guide-demand-label">${s.id==='future_entry'?t('ตลาดอนาคต · ต้องตรวจ Demand','Future market · validate Demand'):t('Demand สูง','High demand')}</span>${points.map(([kind,x,y])=>`<div class="guide-story-node guide-node-${kind}" style="left:${x/4}%;top:${y/2.4}%">${icon(g[kind])}<span>${t(...labels[kind])}</span></div>`).join('')}</div><figcaption>${t('ภาพอธิบายแนวคิด · ไม่ใช่ข้อมูลทำเลจริง','Concept illustration · not real location data')}</figcaption></figure>`;
 }
 function list(values){return `<ul>${(values||[]).map(v=>`<li>${e(copy(v))}</li>`).join('')}</ul>`;}
 function detail(id){const s=registry.strategies.find(x=>x.id===id);if(!s)return index();const i=registry.strategies.indexOf(s),example=s.illustrativeExample||{};return `<header class="strategy-guide-header"><span class="guide-hero-icon">${icon(s.icon)}</span><span class="eyebrow">${String(i+1).padStart(2,'0')} · Strategy</span><h2 id="strategy-guide-title">${e(copy(s.name))}</h2><p class="guide-lead">${e(copy(s.oneSentence))}</p></header>${diagram(s)}<section><h3>${t('ใช้เมื่อไร','When to use it')}</h3><p>${e(copy(s.why))}</p></section><section class="guide-example"><h3>${icon('explore')}${t('ลองนึกภาพ','Picture this')}</h3><p>${e(copy(example.scenario))}</p><p><strong>${t('สิ่งที่ทำต่อ','Next action')}:</strong> ${e(copy(example.action))}</p><p class="guide-disclaimer">${e(copy(example.caveat))}</p></section><section><h3>${t('ลองใช้ใน Yolk','Try it in Yolk')}</h3><ol>${(s.howToUse||[]).map(v=>`<li>${e(copy(v))}</li>`).join('')}</ol></section><section class="guide-evidence"><div><h3>${icon('fact_check')}${t('ข้อมูลที่มีใช้ได้','Evidence available')}</h3>${list(s.availableP0Evidence)}</div><div><h3>${icon('help')}${t('ยังต้องตรวจเพิ่ม','Evidence still needed')}</h3>${list(s.neededEvidence)}</div></section><section><h3>${t('ระวังอะไร','What to watch')}</h3><p>${e(copy(s.tradeoff))}</p><p><strong>${t('คำถามก่อนตัดสินใจ','Question before deciding')}:</strong> ${e(copy(s.question))}</p></section><nav class="guide-pagination" aria-label="${t('อ่าน Strategy อื่น','Explore other strategies')}"><button class="btn" data-guide-id="${e(registry.strategies[(i+7)%8].id)}">${icon('arrow_back')}${t('ก่อนหน้า','Previous')}</button><button class="btn" data-guide-id="${e(registry.strategies[(i+1)%8].id)}">${t('ถัดไป','Next')}${icon('arrow_forward')}</button></nav>`;}
 async function open(id,source){const d=dialog(),request=++ticket;if(!d.open)opener=source||document.activeElement;d.innerHTML=chrome(`<h2 id="strategy-guide-title">${t('กำลังเปิดคู่มือ…','Opening the guide…')}</h2>`);if(!d.open)d.showModal();try{await load();if(request!==ticket||!d.open)return;d.innerHTML=chrome(id?detail(id):index());global.YolkIcons.captionControls(d);d.scrollTop=0;d.querySelector('[data-guide-close]').focus({preventScroll:true});}catch{if(request!==ticket||!d.open)return;d.innerHTML=chrome(`<h2 id="strategy-guide-title">${t('คู่มือยังโหลดไม่สำเร็จ','Guide could not load')}</h2><p>${t('ข้อมูลทำเลยังอยู่ ลองเปิดคู่มืออีกครั้ง','Your location data is intact. Try opening the guide again.')}</p><button class="btn" data-guide-index>${t('ลองใหม่','Retry')}</button>`);d.querySelector('[data-guide-close]').focus({preventScroll:true});}}
 document.addEventListener('click',ev=>{const b=ev.target.closest('[data-guide-id],[data-guide-index],[data-guide-close]');if(!b)return;if(b.hasAttribute('data-guide-close')){dialog().close();return;}ev.preventDefault();ev.stopPropagation();const d=document.getElementById('strategy-guide-dialog');if(d?.open&&registry){d.innerHTML=chrome(b.dataset.guideId?detail(b.dataset.guideId):index());global.YolkIcons.captionControls(d);d.scrollTop=0;d.querySelector('[data-guide-close]').focus({preventScroll:true});}else open(b.dataset.guideId,b);});
 global.YolkStrategyGuide=Object.freeze({open});
})(window);
