/* Strategy is a personal evidence view after Demand screening, never a Demand gate. */
(function(global){
 'use strict';
 let choicesOpen=false;
 const t=(th,en)=>tr(th,en),esc=s=>escapeHTML(s),icon=n=>global.YolkIcons?.icon(n)||'';
 const fallback=['underserved_market','competitive_entry','network_infill'];
 const glyphs={underserved_market:'explore',segment_gap:'groups',competitive_entry:'swords',cluster_participation:'store',complementary_location:'layers',route_capture:'arrow_forward',network_infill:'shield',future_entry:'flag'};
 const preferences=new Map(),cache=new WeakMap();let pageIndex=0;
 function registry(){return global.YOLK_RUNTIME.strategyProfiles||{brands:[],sources:[]};}
 function profile(){return registry().brands.find(b=>b.industryId===Y.industry&&b.brandId===Y.ownBrandId)||null;}
 function scopeProfile(){return profile()?.perScopeProfiles?.[Y.supplyScope]||null;}
 function key(){return criteriaContextKey()+'|strategy-1.9.0';}
 function selectedIds(){if(!preferences.has(key())){let ids;try{ids=JSON.parse(localStorage.getItem('yolk-strategies:'+key())||'null');}catch{}const known=new Set(global.YolkOpportunity?.strategies().map(s=>s.id)||fallback);preferences.set(key(),Array.isArray(ids)&&ids.length&&ids.length<=3&&ids.every(id=>known.has(id))?[...new Set(ids)]:(scopeProfile()?.defaultStrategyIds||profile()?.defaultStrategyIds||fallback).slice(0,3));}return preferences.get(key());}
 function setSelected(ids){if(!Array.isArray(ids)||!ids.length||ids.length>3||new Set(ids).size!==ids.length)return false;const known=new Set(global.YolkOpportunity.strategies().map(s=>s.id));if(ids.some(id=>!known.has(id)))return false;preferences.set(key(),ids.slice());try{localStorage.setItem('yolk-strategies:'+key(),JSON.stringify(ids));}catch{}pageIndex=0;return true;}
 function criteria(){return ['criteria','market','strategy'].includes(Y.route)?draft:Y.criteria;}
 function context(){const supply=global.YOLK_RUNTIME.supplyCache.get(Y.industry);return {industryId:Y.industry,industry:Y.industry,ownBrandId:Y.ownBrandId,supplyScope:Y.supplyScope,sourceRelease:{context:{file:"data/real/area-context.json",sha256:global.YOLK_RUNTIME.sourceHashes?.["area-context"],metadata:global.YOLK_RUNTIME.metadata},supply:{file:"data/real/"+Y.industry+"-supply.json",sha256:global.YOLK_RUNTIME.sourceHashes?.[Y.industry+"-supply"],metadata:supply?.metadata}},profileVersion:registry().version,supplyPeriod:supply?.metadata?.sourcePeriods||supply?.metadata?.period||null,criteriaRevision:criteria().version};}
 function currentView(rows=evaluate(criteria())){const c=criteria(),k=JSON.stringify([key(),selectedIds(),c]);let bucket=cache.get(rows);if(!bucket){bucket=new Map();cache.set(rows,bucket);}if(!bucket.has(k))bucket.set(k,global.YolkOpportunity.view(rows,c,context(),profile(),{strategyIds:selectedIds()}));return bucket.get(k);}
 function candidates(v){return v.rows||v.candidates||v.candidateRows||[];}
 function candidateRow(item){return item.row||item;}
 function assessmentFor(item){return item.assessment||item;}
 function mapRows(rows){const v=currentView(rows),ids=new Set(candidates(v).map(item=>candidateRow(item).id));return rows.map(a=>({...a,eligible:ids.has(a.id),strategyCandidate:ids.has(a.id)}));}
 function copy(value){if(value?.title)return copy(value.title);return typeof value==='string'?value:t(value?.th||'',value?.en||value?.th||'');}
 function name(id){const s=global.YolkOpportunity?.strategies().find(s=>s.id===id);return copy(s?.name||s?.label||{th:id,en:id});}
 function mapSummary(){const v=currentView(),n=candidates(v).filter(item=>inMapArea(candidateRow(item))).length;return selectedIds().map(name).join(' + ')+' · '+num(n)+' '+t('ทำเลที่ชวนสำรวจ · ไม่ใช่ผลยืนยันเปิดสาขา','areas to investigate · not approval to open');}
 function stateLabel(s){return s==='candidate_to_check'?t('ชวนสำรวจ','Investigate'):s==='evidence_incomplete'?t('ต้องเพิ่มหลักฐาน','More evidence needed'):s==='not_current_yolk'?t('ยังไม่ผ่าน Demand','Outside current Demand'):t('ยังไม่พบสัญญาณตรงวิธีนี้','No supporting signal yet');}
 function strategyCards(){const rows=evaluate(criteria()).filter(inMapArea),v=currentView(rows),selected=selectedIds();return `<fieldset class="strategy-choices"><legend>${t('อยากขยายด้วยวิธีไหน? เลือก 1–3 วิธี','How will you expand? Choose 1–3 strategies')}</legend><p class="strategy-choice-help">${t('พื้นที่เดียวเข้ากับหลายวิธีได้ แต่ทุกวิธีต้องมีหลักฐานของตัวเอง','A location can fit several strategies. Each needs its own evidence.')}</p><div class="strategy-card-grid">${global.YolkOpportunity.strategies().map((s,index)=>{const single=global.YolkOpportunity.view(rows,criteria(),context(),profile(),{strategyIds:[s.id]}),count=candidates(single).length,ready=['underserved_market','competitive_entry','complementary_location','network_infill'].includes(s.id);return `<div class="strategy-choice-shell"><label class="strategy-choice ${selected.includes(s.id)?'is-selected':''}"><input type="checkbox" data-strategy-id="${s.id}" ${selected.includes(s.id)?'checked':''} ${!selected.includes(s.id)&&selected.length>=3?'disabled':''}><span class="strategy-choice-title">${icon(glyphs[s.id])}<strong>${String(index+1).padStart(2,'0')} · ${name(s.id)}</strong></span><span>${copy(s.summary||s.description)}</span><small>${ready?num(count)+' '+t('ทำเลชวนสำรวจในขอบเขตนี้','areas to investigate in this scope'):t('มีแบบสำรวจ · รอข้อมูลเพิ่ม','Survey guide · additional data needed')}</small></label><button type="button" class="strategy-guide-button" data-guide-id="${s.id}">${icon('help')}${t('ดูภาพและตัวอย่าง','Illustration & example')}</button></div>`}).join('')}</div><p class="strategy-choice-limit" role="status">${selected.length} / 3 · ${t('ปรับมุมมองส่วนตัว ไม่เปลี่ยน Demand หรือเกณฑ์ทีม','Personal view; Demand and team criteria remain unchanged')}</p></fieldset>`;}
 function scopeLabel(){const labels={all_fuel:['สถานีในบัญชีต้นทาง','Source fuel inventory'],C_STORE:['ร้านสะดวกซื้อ / mini-format','Convenience / mini-format'],SUPERMARKET:['ซูเปอร์มาร์เก็ต','Supermarket'],HYPERMARKET:['ไฮเปอร์มาร์เก็ต','Hypermarket'],WHOLESALE:['ค้าส่ง','Wholesale'],potential_retail_branch_service:['กลุ่มใบอนุญาต retail','Potential retail-license family'],office_context:['บัญชีสำนักงาน','Source office inventory'],vehicle_title:['สินเชื่อทะเบียนรถ','Vehicle-title license'],personal:['สินเชื่อส่วนบุคคล','Personal-loan license'],nano:['Nano','Nano'],pico:['Pico','Pico'],pico_plus:['Pico Plus','Pico Plus']};return labels[Y.supplyScope]?t(...labels[Y.supplyScope]):Y.supplyScope;}
 function evidenceList(a){const refs=a.evidenceRefs||[],labels={demand_proxy_tier:t('ระดับ Demand','Demand tier'),own_branches:t('โล่ · สาขาเรา','Shield · our stores'),competitor_branches:t('ดาบ · คู่แข่ง','Swords · competitors')};return `<dl class="strategy-evidence">${refs.slice(0,3).map(e=>{const m=METRIC_INDEX[e.metricId],label=m?.[Y.lang]||labels[e.metricId]||t('หลักฐานต้นทาง','Source evidence'),unit=m?.[Y.lang==='th'?'unitTh':'unitEn']||(e.unit==='branches'?t('สาขา','stores'):e.unit==='ordinal tier'?'':copy(e.unit)),value=e.metricId==='demand_proxy_tier'?'Tier '+e.value:Number.isFinite(e.value)?num(e.value,Number.isInteger(e.value)?0:2):Number.isFinite(e.lower)?num(e.lower,0)+(e.upper!==e.lower?'–'+(Number.isFinite(e.upper)?num(e.upper,0):'?'):''):'—',period=m?.display?.[Y.lang==='th'?'periodTH':'periodEN']||(typeof e.sourcePeriod==='string'?e.sourcePeriod:'');return `<div><dt>${esc(label)}</dt><dd>${value} ${esc(unit)}</dd>${period?`<small>${esc(period)}</small>`:''}</div>`;}).join('')}</dl>`;}
 function findings(a){return `<div class="strategy-findings"><div><h4>${icon('fact_check')}${t('พบแล้ว','Found')}</h4>${(a.reasons||[]).slice(0,3).map(r=>`<p>${esc(copy(r))}</p>`).join('')}${evidenceList(a)}</div><div><h4>${icon('help')}${t('ยังไม่รู้','Still unknown')}</h4><ul>${(a.missingEvidence||[]).slice(0,3).map(r=>`<li>${esc(copy(r))}</li>`).join('')}</ul></div><div><h4>${icon('explore')}${t('งานแรก','First field task')}</h4><p>${esc(copy(a.nextAction?.title||a.nextAction))}</p></div></div>`;}
 function activeAssessments(result){return (result.assessments||[]).filter(a=>selectedIds().includes(a.strategyId));}
 function resultCard(item,index){
  const row=candidateRow(item),result=assessmentFor(item),as=activeAssessments(result).filter(a=>a.status==='candidate_to_check'),saved=Y.targets[row.id]&&!Y.targets[row.id].archived,lead=as[0];
  return `<article class="strategy-result"><header><span class="rank">${index+1}</span><div><button class="location-title" data-action="place" data-id="${row.id}">${esc(areaName(row.id))}</button><small>${esc(provinceName(row.province))} · ${YolkDecisions.tierText(row)}</small></div></header><div class="strategy-result-tags">${as.map(a=>`<button class="strategy-tag-button" data-guide-id="${a.strategyId}" aria-label="${t('อ่านเพิ่ม: ','Read more: ')+esc(name(a.strategyId))}">${icon(glyphs[a.strategyId])}${name(a.strategyId)}</button>`).join('')}</div>${lead?`<p class="opportunity-reason">${icon('fact_check')}${esc(copy(lead.reasons?.[0]))}</p><details class="opportunity-evidence"><summary>${icon('search')}${t('ดูเหตุผลและงานสำรวจ','See reasons & fieldwork')}</summary>${findings(lead)}</details>`:''}<div class="strategy-actions"><button class="btn" data-action="place" data-id="${row.id}">${icon('location_on')}${t('ดูทำเล','View place')}</button><button class="btn primary" data-strategy-action="save" data-id="${row.id}" ${canEdit()?'':'disabled'}>${icon(saved?'bookmark_added':'bookmark_add')}${saved?t('บันทึกแผนสำรวจ','Save survey plan'):t('เล็งทำเล','Shortlist')}</button></div></article>`;
 }

 function brandPanel(){const b=profile(),p=scopeProfile();if(!b)return '';const sources=registry().sources||registry().sourceRefs||[],sourceIds=[...new Set([...(b.sourceIds||[]),...(p?.sourceIds||[])])];return `<section class="section strategy-brand-profile"><div class="block-title"><h2>${global.YolkBrands.logo(Y.ownBrandId)}${esc(global.YolkBrands.displayName(Y.ownBrandId,ownBrandName()))}</h2><span class="tag">${t('โปรไฟล์แบรนด์','Brand profile')}</span></div><p><strong>${t('ขอบเขต Supply','Supply scope')}:</strong> ${esc(scopeLabel())}</p><p>${esc(copy(p?.offeringSummary||b.offeringSummary||b.positioning?.operatorClaim))}</p><p class="footline">${t('เริ่มจากธุรกิจและรูปแบบเดียวกัน ส่วนช่องว่างกลุ่มลูกค้าต้องตรวจสินค้า ราคา เวลาเปิด และการเข้าถึงเพิ่ม','Compare like-for-like submarkets first. A customer-segment gap still needs product, price, hours and access evidence.')}</p><details><summary>${icon('fact_check')}${t('ข้อเสนอของแบรนด์และที่มาของ preset','Offering and preset rationale')}</summary><p>${esc(copy(b.positioning?.operatorClaim))}</p><p>${esc(copy(p?.rationale||b.presetRationale))}</p>${(b.limitations||[]).slice(0,3).map(l=>`<p>${esc(copy(l))}</p>`).join('')}<p>${t('ตัวเลขเป็นสมมติฐานของ Yolk ไม่ใช่ค่าที่แบรนด์รับรอง ภาพลักษณ์จากคำกล่าวของแบรนด์ยังไม่ใช่ผลสำรวจการรับรู้ของลูกค้า','Numeric presets are Yolk hypotheses, not brand-endorsed rules. Operator positioning is not measured consumer perception.')}</p>${sourceIds.map(id=>sources.find(s=>s.id===id)).filter(Boolean).map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title||s.id)} ${icon('open_in_new')}</a>`).join('')}</details></section>`;}
 function page(){
  const rows=evaluate(criteria()),v=currentView(rows),scoped=candidates(v).filter(item=>inMapArea(candidateRow(item)));
  pageIndex=Math.min(pageIndex,Math.max(0,Math.ceil(scoped.length/6)-1));
  const offset=pageIndex*6,eligible=rows.filter(a=>a.eligible&&inMapArea(a)).length,shortlisted=Object.values(Y.targets).filter(a=>!a.archived).length,isDraft=diffCriteria(Y.criteria,criteria()).length>0;
  return `<div class="page-head opportunity-head"><div><h1>${icon('explore')}${t('โอกาสขยาย','Expansion opportunities')}</h1><p>${t('เริ่มจาก preset ของแบรนด์ ดูเหตุผล แล้วเล็งทำเลที่อยากไปสำรวจ','Your brand preset is ready. See the evidence, then shortlist a place to explore.')}</p></div></div>
  <div class="strategy-counters opportunity-counters" role="status"><div><strong>${num(eligible)}</strong><span>${t('ไข่แดงผ่าน Demand','Demand-qualified Yolks')}</span></div><div><strong>${num(scoped.length)}</strong><span>${t('ทำเลชวนสำรวจ','Places to investigate')}</span></div></div>
  <p class="opportunity-scope">${icon('map')}${esc(mapNavigationTitle())} · ${t('สีไข่ดาว = ระดับ Demand ของทำเลที่เข้ากับวิธีที่เลือก','Egg colour = Demand tier for candidates matching your approach')}</p>
  ${isDraft?`<p class="strategy-map-reading"><strong>${t('กำลังดูแบบร่างส่วนตัว','Viewing a private draft')}</strong> · ${t('เกณฑ์ทีมยังไม่เปลี่ยน','Team criteria are unchanged')} <a href="#criteria">${t('ตรวจค่าที่ปรับ','Review changes')}</a></p>`:criteria().criteriaModeVersion!=="1.9.0"?`<p class="strategy-map-reading">${t('ใช้เกณฑ์ที่เคยบันทึก','Using saved criteria')} · <a href="#criteria">${t('ลอง preset ใหม่','Try a new preset')}</a></p>`:''}
  <details class="opportunity-strategy-picker" data-strategy-picker ${choicesOpen?'open':''}><summary>${icon('tune')}<span>${t('วิธีขยาย','Expansion approach')}: ${selectedIds().map(name).join(' + ')}</span></summary><div data-strategy-choices-content>${choicesOpen?strategyCards():''}</div></details>
  <div class="strategy-guide-entry"><button class="strategy-guide-button" data-guide-index>${icon('help')}${t('รู้จัก 8 Strategy','Meet the 8 strategies')}</button></div>
  <section class="strategy-results"><h2>${t('เริ่มดูทำเลเหล่านี้','Start with these places')}</h2><p>${t('ดูเหตุผล → เล็งทำเล → ตรวจหน้างาน ก่อนตัดสินใจเปิดสาขา','See the evidence → shortlist → validate in the field before deciding to open.')}</p><details class="opportunity-sort"><summary>${icon('tune')}${t('เรียงลำดับอย่างไร','How are these ordered?')}</summary><p>${copy(v.sortDescription)}</p></details>
  ${scoped.slice(offset,offset+6).map((r,i)=>resultCard(r,offset+i)).join('')||`<div class="empty"><h3>${t('ยังไม่มีทำเลที่มีหลักฐานตรงวิธีนี้','No supported candidate for this approach yet')}</h3><p>${t('ลองวิธีขยายอื่น หรือดูไข่แดงทั้งหมดใน Demand จำนวนไข่แดงเดิมไม่เปลี่ยน','Try another approach or explore all Yolks in Demand. Your Demand results are unchanged.')}</p><a class="btn" href="#demand">${icon('egg_alt')}${t('ดูไข่แดงทั้งหมด','Explore Demand Yolks')}</a></div>`}
  <div class="pagination"><button class="btn" data-strategy-action="prev" ${pageIndex?'':'disabled'}>${t('ก่อนหน้า','Previous')}</button><span>${num(scoped.length)} · ${pageIndex+1} / ${Math.max(1,Math.ceil(scoped.length/6))}</span><button class="btn" data-strategy-action="next" ${offset+6<scoped.length?'':'disabled'}>${t('ถัดไป','Next')}</button></div></section>
  <details class="section opportunity-profile"><summary>${icon('store')}${t('โปรไฟล์แบรนด์และที่มาของ preset','Brand profile & preset sources')}</summary>${brandPanel()}</details>
  <details class="section opportunity-limits"><summary>${icon('help')}${t('ข้อมูลที่ยังต้องเพิ่ม','Evidence still needed')}</summary><p>${t('ผลนี้เป็นคิวสำรวจ ไม่ใช่การรับรองว่าร้านใหม่จะขายดี พื้นที่โปร่งบนแผนที่อาจไม่ตรง Strategy ไม่ได้แปลว่า Demand ต่ำ','This is a fieldwork queue, not a sales forecast. An unfilled area may fall outside the chosen strategy; it does not imply low Demand.')}</p>${selectedIds().map(id=>{const sample=rows.find(r=>r.eligible&&inMapArea(r)),a=sample?global.YolkOpportunity.assess(sample,criteria(),context(),profile(),{strategyIds:[id]}).assessments.find(a=>a.strategyId===id):null;return `<details><summary>${icon(glyphs[id])}${name(id)}</summary>${a?findings(a):''}</details>`}).join('')}<p class="footline">${t('โรงงานและโรงแรมเป็นบริบทพื้นที่ โรงพยาบาล โรงเรียน พิกัด anchor และการเดินทางของลูกค้ายังต้องเชื่อมข้อมูลเพิ่ม Future entry ไม่เพิ่มไข่แดงปัจจุบัน','Factories and hotels are area context. Hospital/school anchors and customer flows still need additional evidence. Future entry never adds current Yolks.')}</p></details>`;
 }

 function snapshot(id){const row=evaluate(criteria()).find(a=>a.id===id);if(!row)return null;const result=global.YolkOpportunity.assess(row,criteria(),context(),profile(),{strategyIds:selectedIds()});return {version:'1.9.0',engineVersion:result.engineVersion,strategyContractVersion:result.strategyContractVersion,profileId:profile()?.id,profileVersion:registry().version,reportingAreaId:id,context:context(),strategyIds:selectedIds().slice(),criteria:structuredClone(criteria()),criteriaStatus:diffCriteria(Y.criteria,criteria()).length?'private_draft':'team_revision',assessedAt:new Date().toISOString(),status:result.status,assessments:structuredClone(result.assessments),sourceRelease:global.YOLK_RUNTIME.metadata,notInvestmentApproval:true};}
 function detail(a){const result=global.YolkOpportunity.assess(a,Y.criteria,context(),profile(),{strategyIds:selectedIds()}),saved=Y.targets[a.id]?.strategyAssessment;return `<section class="section location-strategies"><h2>${icon('explore')}${t('วิธีที่ชวนตรวจในทำเลนี้','Strategies to investigate here')}</h2><p>${t('แนวทางสำรวจจากข้อมูลที่มี ไม่ใช่ข้อสรุปว่าร้านใหม่จะขายดี','An evidence-based research plan, not a prediction that the new branch will sell well.')}</p>${activeAssessments(result).map(as=>`<details ${as.status==='candidate_to_check'?'open':''}><summary>${icon(glyphs[as.strategyId])}${name(as.strategyId)} · ${stateLabel(as.status)}</summary>${findings(as)}</details>`).join('')}${saved?`<p class="footline">${t('แผนที่บันทึกไว้เมื่อ','Plan captured at')} ${esc(new Date(saved.assessedAt).toLocaleString(Y.lang==='th'?'th-TH':'en-GB'))} · ${t('ตามเกณฑ์','Criteria')} v${saved.criteria?.version} · ${saved.criteriaStatus==='private_draft'?t('แบบร่างส่วนตัว','Private draft'):t('รุ่นที่ทีมบันทึก','Saved team revision')} · ${saved.strategyIds.map(name).join(', ')}</p>`:''}<a class="btn" href="#market">${icon('tune')}${t('เลือก Strategy','Choose strategies')}</a></section>`;}
 global.YolkStrategyUI=Object.freeze({page,detail,profile,scopeProfile,brandPanel,selectedIds,setSelected,currentView,mapRows,mapSummary,snapshot,criteria});
 document.addEventListener('toggle',e=>{if(!e.target.matches?.('[data-strategy-picker]'))return;choicesOpen=e.target.open;if(choicesOpen){const content=e.target.querySelector('[data-strategy-choices-content]');if(content&&!content.innerHTML){content.innerHTML=strategyCards();global.YolkIcons?.captionControls(content);}}},true);
 document.addEventListener('change',e=>{const input=e.target;if(!input.matches('[data-strategy-id]'))return;const ids=selectedIds().filter(id=>id!==input.dataset.strategyId);if(input.checked)ids.push(input.dataset.strategyId);if(!setSelected(ids)){input.checked=!input.checked;notify(t('เลือก 1–3 Strategy','Choose 1–3 strategies'));return;}render();document.querySelector(`[data-strategy-id="${input.dataset.strategyId}"]`)?.focus();});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-strategy-action]');if(!b||b.disabled)return;const action=b.dataset.strategyAction;if(action==='prev'||action==='next'){pageIndex=Math.max(0,pageIndex+(action==='next'?1:-1));render();return;}if(action==='save'&&canEdit()){const id=b.dataset.id,old=Y.targets[id],beforeCount=global.YolkActionGuidance?.count(Y.targets),source=global.YolkActionGuidance?.capture(b),plan=snapshot(id);if(!plan)return;const next={...(old||{owner:Y.actor,status:'study',note:''}),archived:false,strategyAssessment:plan};Y.targets[id]=next;const event=emitEvent(old&&!old.archived?'place.updated':'place.created','place',id,[{field:'strategyAssessment',before:old?.strategyAssessment||null,after:plan}],{strategyIds:plan.strategyIds,criteriaStatus:plan.criteriaStatus});if(!event){if(old)Y.targets[id]=old;else delete Y.targets[id];return;}render();committed(!!global.YolkActionGuidance);global.YolkActionGuidance?.shortlistSaved({event,source,beforeCount,afterCount:global.YolkActionGuidance.count(Y.targets),name:areaName(id),lang:Y.lang,plan:true});}});
})(window);
