/* Synthetic branch examples; aggregate supply remains a demo analytical baseline. */
function areaOptions(province, selected = '') {
  const rows = AREAS.filter(a => a.province === province).sort((a,b) => areaName(a.id).localeCompare(areaName(b.id), Y.lang === 'en' ? 'en' : 'th'));
  return `<option value="">${tr('เลือกแขวง / อปท.','Choose a khwaeng / local authority')}</option>` + rows.map(a => `<option value="${escapeHTML(a.id)}" ${a.id === selected ? 'selected' : ''}>${escapeHTML(areaName(a.id))}</option>`).join('');
}
function supplyIsImported(p) { return ['gasStation','gasStationS'].includes(p.sourceDataset); }
function supplyIsDemo(p) { return p.sourceDataset === 'synthetic_demo'; }
function supplyStatusLabel(p) { return valLabels[p.status] ? tr(...valLabels[p.status]) : tr('ยังไม่ระบุสถานะ','Status not specified'); }
function supplyObservedLabel(p) {
  if (supplyIsDemo(p)) return tr('ข้อมูลจำลอง','Synthetic demo record');
  if (!p.observedAt || !Number.isFinite(Date.parse(p.observedAt))) return tr('รายการที่ทีมเพิ่ม','Added by the team');
  return tr('อ่านข้อมูล ','Read ') + new Intl.DateTimeFormat(Y.lang === 'en' ? 'en-GB' : 'th-TH', {day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Bangkok'}).format(new Date(p.observedAt));
}
function supplySourceLink(p) {
  return p.sourceUrl && /^https:\/\/landometer\.com\//.test(p.sourceUrl) ? `<a class="quiet-link" href="${escapeHTML(p.sourceUrl)}" target="_blank" rel="noopener noreferrer">${tr('เปิดหลักฐานต้นทาง','Open source record')} ↗</a>` : '';
}
function supply() {
  const q=Y.poiQuery.trim().toLocaleLowerCase(), matchesTab=(p,t)=>t==='archived'?p.archived:!p.archived&&(t==='all'||(t==='unverified'?(p.relation==='unverified'||p.status==='pending'):p.relation===t));
  let rows=Y.pois.filter(p=>matchesTab(p,Y.poiTab)&&(!Y.poiArea||p.area===Y.poiArea)&&(!Y.brandFilter||p.brand===Y.brandFilter)&&(`${branchName(p)} ${p.brand||''} ${areaName(p.area)} ${provinceName(AREA_INDEX.get(p.area)?.province||p.province)}`.toLocaleLowerCase().includes(q)));
  const brands=[...new Set(Y.pois.filter(p=>!p.archived).map(p=>p.brand).filter(Boolean))].sort(), totalPages=Math.max(1,Math.ceil(rows.length/12));
  Y.page=Math.min(Math.max(0,Y.page),totalPages-1);
  const page=rows.slice(Y.page*12,Y.page*12+12), labels={branch:tr('สาขา / แบรนด์','Branch / brand'),relationship:tr('ประเภท','Relationship'),area:tr('ทำเล','Location'),status:tr('สถานะข้อมูล','Record status'),manage:tr('จัดการ','Manage')};
  return `<div class="page-head"><div><h1>${tr('สาขาบางจากและคู่แข่ง','Bangchak and competitor branches')}</h1><p>${tr('ค้นหา ตรวจสอบ และบันทึกข้อมูลสาขาร่วมกันทั้งทีม','Find, verify, and maintain branch records together.')}</p></div><button class="btn primary" data-action="new-poi" ${!canEdit()?'disabled':''}>${tr('เพิ่มสาขา','Add branch')}</button></div>
  <div class="notice"><strong>${tr('ตัวอย่างสาขาจำลองสำหรับทดลองระบบ','Synthetic branch examples for the product demo')}</strong><p>${tr('ชื่อสาขา จำนวน และตัววัดในตัวอย่างนี้เป็นข้อมูลจำลอง ไม่มีพิกัดสถานีจริง','Names, counts and metrics in this example are synthetic; no real station coordinates are included.')}</p><p class="footline">${tr('ผลวิเคราะห์ยังใช้ยอดรวมจำลองที่ตั้งไว้ การแก้สาขาจะเข้าคิวกระทบยอดก่อนเปลี่ยน Supply ที่ใช้คัดทำเล','Analysis uses pinned synthetic totals. Branch edits enter reconciliation before changing screening supply.')}</p></div>
  ${Y.poiArea?`<div class="notice">${escapeHTML(provinceName(AREA_INDEX.get(Y.poiArea)?.province))} · ${escapeHTML(areaName(Y.poiArea))}<button class="btn" data-action="clear-area">${tr('ล้างตัวกรองทำเล','Clear location filter')}</button></div>`:''}
  <div class="supply-tabs" role="group" aria-label="${tr('ประเภทสาขา','Branch filters')}">${[['all','ทั้งหมด','All'],['own','สาขาบางจาก','Bangchak'],['competitor','คู่แข่ง','Competitors'],['unverified','รอตรวจสอบ','Unverified'],['archived','คลัง','Archived']].map(([id,th,en])=>`<button aria-pressed="${Y.poiTab===id}" data-action="supply-tab" data-tab="${id}" class="${Y.poiTab===id?'active':''}">${tr(th,en)}<span>${Y.pois.filter(p=>matchesTab(p,id)).length}</span></button>`).join('')}</div>
  <div class="filters"><label class="search"><input id="poi-search" value="${escapeHTML(Y.poiQuery)}" aria-label="${tr('ค้นหาสาขา','Search branches')}" placeholder="${tr('ค้นหาชื่อสาขา แบรนด์ หรือจังหวัด','Search branch, brand or province')}"></label><div class="select-wrap"><label for="brand-filter">${tr('แบรนด์','Brand')}</label><select id="brand-filter"><option value="">${tr('ทุกแบรนด์','All brands')}</option>${brands.map(b=>`<option value="${escapeHTML(b)}" ${Y.brandFilter===b?'selected':''}>${escapeHTML(b)}</option>`).join('')}</select></div><span class="small" role="status">${num(rows.length)} ${tr('รายการ','records')}</span></div>
  <div class="supply-table-wrap"><table class="supply-table"><thead><tr>${Object.values(labels).map(l=>`<th scope="col">${l}</th>`).join('')}</tr></thead><tbody>${page.map(p=>`<tr><td data-label="${labels.branch}"><strong>${escapeHTML(branchName(p))}</strong><small>${escapeHTML(p.brand==='UNKNOWN'||!p.brand?tr('ต้นทางไม่ระบุแบรนด์','Brand unknown in source'):p.brand)}</small><small>${escapeHTML(supplyObservedLabel(p))}</small></td><td data-label="${labels.relationship}"><span class="tag ${p.relation==='own'?'high':p.relation==='unverified'?'wait':''}">${valLabels[p.relation]?tr(...valLabels[p.relation]):tr('รอจัดประเภท','Unclassified')}</span></td><td data-label="${labels.area}">${escapeHTML(areaName(p.area))}<small>${escapeHTML(provinceName(AREA_INDEX.get(p.area)?.province||p.province))}</small></td><td data-label="${labels.status}"><span class="tag ${p.status==='active'?'high':p.status==='pending'?'wait':''}">${supplyStatusLabel(p)}</span>${supplyIsImported(p)&&p.status==='source'?`<small>${tr('ยังไม่ยืนยันว่าเปิดอยู่ปัจจุบัน','Current operating status unverified')}</small>`:''}</td><td data-label="${labels.manage}"><button class="btn small-button" data-action="edit-poi" data-id="${escapeHTML(p.id)}">${canEdit()?tr('ดู / แก้ไข','View / edit'):tr('ดูข้อมูล','View')}</button>${canEdit()?`<button class="quiet-link" data-action="${p.archived?'restore-poi':'archive-poi'}" data-id="${escapeHTML(p.id)}">${p.archived?tr('คืนรายการ','Restore'):tr('เก็บเข้าคลัง','Archive')}</button>`:''}</td></tr>`).join('')}</tbody></table>${!rows.length?`<div class="empty"><h3>${tr('ไม่พบรายการที่ตรงกับตัวกรอง','No matching records')}</h3><p>${tr('ลองเปลี่ยนคำค้นหรือแบรนด์ พื้นที่อื่นอาจมีจำนวนสาขาจำลองแม้ไม่มีรายการรายสาขา','Try another search or brand. Other demo areas may have aggregate counts without individual branch records.')}</p></div>`:''}</div>
  <div class="pagination"><button class="btn small-button" data-action="poi-prev" ${Y.page===0?'disabled':''}>${tr('ก่อนหน้า','Previous')}</button><span>${Y.page+1} / ${totalPages}</span><button class="btn small-button" data-action="poi-next" ${Y.page+1>=totalPages?'disabled':''}>${tr('ถัดไป','Next')}</button></div><p class="footline">${tr('UNKNOWN หมายถึงยังไม่ทราบแบรนด์ ไม่ใช่สถานี unbranded ที่ตรวจยืนยันแล้ว การเก็บเข้าคลังคงประวัติไว้และไม่ลดยอดรวมจำลองทันที','UNKNOWN means the brand is unidentified, not a verified unbranded station. Archiving preserves history and does not immediately reduce synthetic aggregate totals.')}</p>
  <section class="section full-feed"><h2>${tr('ความเคลื่อนไหวของข้อมูลสาขา','Branch data activity')}</h2>${feed(Y.events.filter(e=>e.entity==='supply'))}</section>`;
}
function poiEditor() {
  const id=location.hash.split('/')[1], existing=Y.pois.find(x=>x.id===id),fresh=!existing;
  const p=existing||{id:'new',name:'',brand:'',relation:'unverified',area:Y.poiArea||Y.selected,status:'pending',lat:'',lng:'',note:'',revision:0};
  const area=AREA_INDEX.get(p.area), province=area?.province||p.province||AREA_INDEX.get(Y.selected)?.province||'10';
  const imported=supplyIsImported(p), demo=supplyIsDemo(p), missingSourceName=imported&&!p.name;
  return `<a class="back" href="#supply">← ${tr('กลับไปข้อมูลสาขา','Back to branches')}</a><div class="page-head"><div><h1>${fresh?tr('เพิ่มสาขาเข้าพื้นที่ทำงาน','Add a branch to the workspace'):escapeHTML(branchName(p))}</h1><p>${tr('บันทึกสิ่งที่ทีมรู้ พร้อมหลักฐานและประวัติการเปลี่ยนแปลง','Record what the team knows, with evidence and a change history.')}</p></div><span class="tag">${demo?tr('ข้อมูลจำลอง','Synthetic demo record'):imported?tr('เริ่มจากข้อมูล CityMETER','Originated from CityMETER'):tr('ข้อมูลที่ทีมเพิ่ม','Team-added record')} · ${fresh?'New':'v'+p.revision}</span></div>
  <div class="detail-grid"><form id="poi-form" class="section" data-id="${escapeHTML(p.id)}" data-revision="${p.revision}" data-source-name-missing="${missingSourceName}"><fieldset ${!canEdit()?'disabled':''}><div class="form-grid">
  <div class="field"><label for="branch-name">${tr('ชื่อสาขา','Branch name')}${fresh?' *':''}</label><input id="branch-name" name="name" ${fresh?'required':''} maxlength="100" value="${escapeHTML(p.name)}" ${missingSourceName?`placeholder="${tr('ต้นทางไม่ระบุชื่อ — ใส่เมื่อยืนยันได้','Missing in source — add once confirmed')}" aria-describedby="name-source-note"`:''}>${missingSourceName?`<small id="name-source-note">${tr('คงว่างไว้ได้จนกว่าจะยืนยันชื่อ ไม่ต้องตั้งชื่อขึ้นใหม่','May remain blank until the name is confirmed.')}</small>`:''}</div>
  <div class="field"><label for="branch-brand">${tr('แบรนด์','Brand')}</label><input id="branch-brand" name="brand" list="brands" maxlength="80" value="${escapeHTML(p.brand)}"><datalist id="brands">${[...new Set(Y.pois.map(x=>x.brand).filter(Boolean))].sort().map(b=>`<option value="${escapeHTML(b)}">`).join('')}</datalist></div>
  <div class="field"><label for="branch-relation">${tr('ประเภทสาขา','Relationship')}</label><select id="branch-relation" name="relation">${['own','competitor','unverified'].map(v=>`<option value="${v}" ${p.relation===v?'selected':''}>${tr(...valLabels[v])}</option>`).join('')}</select></div>
  <div class="field"><label for="branch-status">${tr('สถานะการตรวจสอบ','Verification status')}</label><select id="branch-status" name="status">${['source','pending','active','closed'].map(v=>`<option value="${v}" ${p.status===v?'selected':''} ${v==='source'&&!imported?'disabled':''}>${tr(...valLabels[v])}</option>`).join('')}</select></div>
  <div class="field"><label for="branch-province">${tr('จังหวัด','Province')} *</label><select id="branch-province">${P.slice().sort((a,b)=>provinceName(a.code).localeCompare(provinceName(b.code),Y.lang==='en'?'en':'th')).map(a=>`<option value="${escapeHTML(a.code)}" ${province===a.code?'selected':''}>${escapeHTML(provinceName(a.code))}</option>`).join('')}</select></div>
  <div class="field"><label for="branch-area">${province==='10'?tr('แขวง','Khwaeng'):tr('อปท.','Local authority')} *</label><select name="area" id="branch-area" required>${areaOptions(province,p.area)}</select></div>
  <div class="field"><label for="branch-lat">${tr('ละติจูด','Latitude')}</label><input id="branch-lat" name="lat" type="number" min="-90" max="90" step="any" value="${escapeHTML(p.lat)}"></div><div class="field"><label for="branch-lng">${tr('ลองจิจูด','Longitude')}</label><input id="branch-lng" name="lng" type="number" min="-180" max="180" step="any" value="${escapeHTML(p.lng)}"></div>
  <div class="field span-two"><label for="branch-note">${tr('หลักฐาน / บันทึกการตรวจสอบ','Evidence / verification note')}</label><textarea id="branch-note" name="note" rows="4" maxlength="1000" placeholder="${tr('เช่น แหล่งข้อมูล วันที่ตรวจสอบ และสิ่งที่พบ','For example: source, date checked, and findings')}">${escapeHTML(p.note)}</textarea></div></div><p id="form-error" class="form-error" role="alert"></p><div class="form-actions"><button class="btn primary" type="submit">${fresh?tr('เพิ่มและแจ้งทีม','Add & notify team'):tr('บันทึกและแจ้งทีม','Save & notify team')}</button><a class="btn" href="#supply">${tr('ยกเลิก','Cancel')}</a></div></fieldset></form>
  <aside><section class="section"><h2>${tr('ข้อมูลนี้มาจากไหน','Where this record comes from')}</h2>${demo?`<p>${tr('รายการนี้เป็นตัวอย่างจำลอง ไม่มีพิกัดสถานีจริง','This is a synthetic example with no real station coordinates.')}</p>`:imported?`<p><strong>CityMETER · ${escapeHTML(p.sourceDataset)}</strong><br>${escapeHTML(supplyObservedLabel(p))}</p><p>${tr('รายการนี้เริ่มจากข้อมูล CityMETER ค่าปัจจุบันอาจมีการแก้ไขโดยทีม ดูประวัติด้านล่าง สถานะการตรวจสอบแสดงตามที่ทีมบันทึก','This record originated from CityMETER. Current fields may include team changes; see the history below. Verification status follows the team’s recorded status.')}</p>${supplySourceLink(p)}<p class="footline">${p.sourceNameMissing?tr('ต้นทางไม่ระบุชื่อสาขา · ','Source name missing · '):''}${p.sourceDataset==='gasStation'?tr('พิกัดต้นฉบับจาก MVT z14 อาจคลาดเคลื่อนระดับไม่กี่เมตร','Original coordinates were decoded from MVT z14 and may vary by a few metres.'):tr('พิกัดต้นฉบับจากค่า lat/lon ในข้อมูลต้นทาง','Original coordinates came from source lat/lon attributes.')}</p>`:`<p>${tr('รายการใหม่เป็นข้อมูลที่ทีมบันทึก ระบุหลักฐานก่อนยืนยันว่าสาขาเปิดอยู่','This is a team-added record. Add supporting evidence before confirming that the branch is open.')}</p>`}</section>
  <section class="section"><h2>${tr('บันทึกแล้วเกิดอะไรขึ้น','What happens after saving')}</h2><p>${tr('ทีมจะเห็นข้อความใน feed และได้รับแจ้งเตือน การเปลี่ยนแปลงเก็บประวัติไว้ทุกรายการ','The team sees a feed entry and receives a notification. Every committed change keeps its history.')}</p><p>${tr('ผลคัดทำเลยังยึดยอดรวมจำลองไว้ก่อน รายสาขาที่แก้ไขต้องกระทบยอด จึงจะเปลี่ยน Supply ที่ใช้วิเคราะห์','Screening keeps synthetic totals as its baseline. Edited branch records need reconciliation before changing analytical supply.')}</p><p class="footline">${tr('การเก็บเข้าคลังหรือคืนรายการเปลี่ยนรายการทำงานของทีม แต่ยังไม่เปลี่ยนยอดรวมอัตโนมัติ','Archiving or restoring changes the team’s working list, without automatically changing aggregate counts.')}</p></section>
  ${!fresh?`<section class="section"><h2>${tr('ประวัติสาขานี้','This branch’s history')}</h2>${feed(Y.events.filter(e=>e.entity==='supply'&&e.entity_id===p.id),{links:false})}</section>`:''}</aside></div>`;
}
