/* One persistent Leaflet view. Colours express confirmed signal tiers, never measured customers. */
(function (global) {
 'use strict';
 const MAX_POINTS=1000, MAX_AREAS=1500;
 const layerLabels={eligible:['ผ่านเกณฑ์','Qualifying'],baseline:['เกณฑ์ทีม','Team criteria'],added:['เข้าใหม่','Newly qualify'],removed:['หลุดเกณฑ์','No longer qualify'],review:['รอตรวจ','Needs review'],rank:['อันดับเปลี่ยน','Changed ranks']};
 const S={map:null,host:null,panel:null,callbacks:{},provinceGroup:null,districtGroup:null,areaGroup:null,pointGroup:null,badgeGroup:null,draftGroup:null,draftVisible:false,provinceLayers:new Map(),provinceData:null,provincePromise:null,layer:'eligible',show:{own:true,competitor:true,unverified:true},focusedArea:'',focusedPoi:'',lastRoute:'',lastSnapshot:null,syncing:false,focusTicket:0,basemap:'simplified',tileLayer:null,provinceError:'',tileError:'',viewInteracted:false,controlsOpen:false,viewportFrame:null,tokens:null,pointRecords:new Map(),pointContext:'',nav:{level:'country',provinceCode:'',districtId:'',districtName:'',areaId:''},hierarchy:null,hierarchyPromise:null,hierarchyError:'',districtData:null,districtLayers:new Map(),districtIndex:new Map(),districtRecords:new Map(),keyboardElements:new WeakSet(),districtChoices:[],areaRecords:new Map(),fineCache:new Map(),finePending:new Map(),fineErrors:new Map(),navigationHitGroup:null,navigationRecords:new Map(),hover:null,analysis:null,analysisFine:null,analysisDistrict:null,nativeDistrictCache:new Map(),nativeDistrictPending:new Map(),nativeDistrictErrors:new Map()};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const text=(th,en)=>typeof tr==='function'?tr(th,en):th;
 const icon=name=>global.YolkIcons?.icon(name)||'';
 const number=n=>Number(n).toLocaleString(Y.lang==='en'?'en-US':'th-TH');
 const TOKEN_NAMES=['--yl-yolk-map-1','--yl-yolk-map-2','--yl-yolk-map-3','--no-result','--yl-border-strong','--yl-map-active'];
 const value=name=>S.tokens?.[name]??global.getComputedStyle(S.panel||global.document.documentElement).getPropertyValue(name).trim();
 function readTokens(){const style=global.getComputedStyle(S.panel||global.document.documentElement);S.tokens=Object.fromEntries(TOKEN_NAMES.map(name=>[name,style.getPropertyValue(name).trim()]));}
 const requestFrame=callback=>typeof global.requestAnimationFrame==='function'?global.requestAnimationFrame(callback):global.setTimeout(callback,16);
 const cancelFrame=frame=>typeof global.cancelAnimationFrame==='function'?global.cancelAnimationFrame(frame):global.clearTimeout(frame);
 function cancelViewportRefresh(){if(S.viewportFrame!==null){cancelFrame(S.viewportFrame);S.viewportFrame=null;}}
 function queueViewportRefresh(){if(S.viewportFrame!==null)return;S.viewportFrame=requestFrame(()=>{S.viewportFrame=null;if(!S.map||S.syncing||Y.loading||Y.loadError||!S.lastSnapshot)return;if(S.nav.level!=='location'&&Y.route!=='poi')return;const points=drawPoints(),areas=S.lastAreaCounts||{shown:0,total:0};updateCounts(points.shown,points.total,areas.shown,areas.total);});}
 const tierClass=t=>[1,2,3].includes(t)?4-t:null;
 const tierColor=t=>{const k=tierClass(t);return k?(global.YolkTierStyle?.paint(t)||value('--yl-yolk-map-'+k)):value('--no-result')};
 const validPoint=p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)&&Math.abs(p.lat)<=90&&Math.abs(p.lng)<=180;
 function extentBounds(e){if(!Array.isArray(e)||e.length!==4||!e.every(Number.isFinite)||e[0]>e[2]||e[1]>e[3])return null;const lon=x=>x/6378137*180/Math.PI,lat=y=>(2*Math.atan(Math.exp(y/6378137))-Math.PI/2)*180/Math.PI;return [[lat(e[1]),lon(e[0])],[lat(e[3]),lon(e[2])]];}
 function snapshot(){
  const oldRows=evaluate(Y.criteria),criteria=Y.route==='criteria'?draft:Y.criteria,nextRows=evaluate(criteria),old=oldRows.filter(a=>a.eligible),next=nextRows.filter(a=>a.eligible);
  const oldIDs=new Set(old.map(a=>a.id)),nextIDs=new Set(next.map(a=>a.id)),oldRanks=new Map(old.map((a,i)=>[a.id,i+1])),nextRanks=new Map(next.map((a,i)=>[a.id,i+1]));
  return {oldRows,nextRows,old,next,oldIDs,nextIDs,oldRanks,nextRanks,added:next.filter(a=>!oldIDs.has(a.id)),removed:old.filter(a=>!nextIDs.has(a.id)),review:nextRows.filter(a=>a.reviewCandidate||a.demand===null),moved:next.filter(a=>oldRanks.has(a.id)&&oldRanks.get(a.id)!==nextRanks.get(a.id)),criteria};
 }
 function targetRows(rows){return rows.filter(a=>Y.targets[a.id]&&!Y.targets[a.id].archived);}
 function eventRows(rows){const ids=new Set();for(const event of Y.events){if(event.meta?.industry&&event.meta.industry!==Y.industry)continue;if(event.entity==='place')ids.add(event.entity_id);if(event.meta?.area)ids.add(event.meta.area);if(event.meta?.previousArea)ids.add(event.meta.previousArea);}return rows.filter(a=>ids.has(a.id));}
 function displayedRows(s){if(['demand','supply'].includes(Y.route))return s.nextRows;if(Y.route==='targets')return targetRows(s.nextRows);if(['feed','inbox'].includes(Y.route))return eventRows(s.nextRows);if(S.layer==='baseline')return s.old;if(S.layer==='added')return s.added;if(S.layer==='removed')return s.removed;if(S.layer==='review')return s.review;if(S.layer==='rank')return s.moved;return s.next;}
 function provinceSummary(rows,allRows){const result=new Map();for(const p of global.YOLK_PROVINCES||[])result.set(String(p.code),{code:String(p.code),rows:[],bestTier:null,review:0});for(const a of rows){const code=String(a.province);if(!result.has(code))result.set(code,{code,rows:[],bestTier:null,review:0});const item=result.get(code);item.rows.push(a);if(a.eligible&&a.demand===true&&[1,2,3].includes(a.qualifyingTier))item.bestTier=item.bestTier===null?a.qualifyingTier:Math.min(item.bestTier,a.qualifyingTier);}for(const a of allRows){if(a.reviewCandidate||a.demand===null){const item=result.get(String(a.province));if(item)item.review++;}}return result;}
 async function loadNativeDistricts(industry){
  if(S.nativeDistrictCache.has(industry)||S.nativeDistrictPending.has(industry)||S.nativeDistrictErrors.has(industry))return;
  const task=(async()=>{try{const response=await fetch('data/real/'+industry+'-district-supply.json',{cache:'no-store'});if(!response.ok)throw Error('District Supply HTTP '+response.status);const data=await response.json();if(data.metadata?.grain!=='DISTRICT'||!Array.isArray(data.rows))throw Error('Invalid district supply grain');S.nativeDistrictCache.set(industry,data);S.nativeDistrictErrors.delete(industry);}catch(error){S.nativeDistrictErrors.set(industry,String(error.message));}finally{S.nativeDistrictPending.delete(industry);if(Y.industry===industry&&!Y.loading){sync();S.callbacks.onAnalysisReady?.();}}})();S.nativeDistrictPending.set(industry,task);return task;
 }
 function prepareAnalysis(s){
  S.analysis=['demand','supply'].includes(Y.route)&&global.YolkMapAnalysis&&global.YolkAnalysisUI?global.YolkAnalysisUI.state():null;S.analysisFine=null;S.analysisDistrict=null;S.analysisDemandDistricts=new Map();
  if(!S.analysis)return;
  S.analysisFine=global.YolkMapAnalysis.prepare(s.nextRows,S.analysis,s.criteria,{cohortId:'national_fine_7954',cohortRows:s.nextRows});
  if(S.analysis.kind==='demand'){for(const a of s.nextRows){const r=S.analysisFine.records.get(a.id);if(!r?.exact)continue;for(const id of areaDistricts(a)){const prior=S.analysisDemandDistricts.get(id);if(!prior||(S.analysis.metric==='tier'?r.value<prior.value:r.value>prior.value))S.analysisDemandDistricts.set(id,r);}}}
  if(S.analysis.kind==='supply'){
   const data=S.nativeDistrictCache.get(Y.industry);if(data){const rows=global.YolkAnalysisUI.districtRows(data);S.analysisDistrict=global.YolkMapAnalysis.prepare(rows,S.analysis,s.criteria,{cohortId:'national_native_district_928',cohortRows:rows});}
   else loadNativeDistricts(Y.industry);
  }
 }
 function analysisRecordLabel(record){return record?global.YolkAnalysisUI.formatted(record)+' '+global.YolkAnalysisUI.unit(record)+(record.state==='review'?' · '+text('รอตรวจ','Needs review'):record.state==='missing'?' · '+text('ไม่มีข้อมูล','No data'):''):text('ยังไม่มีข้อมูล','No data yet');}
 function districtDemandRecord(id){return S.analysisDemandDistricts?.get(id)||null;}

 function usableGeometry(a){const feature=a?.mapContext?.boundary;return feature&&['Polygon','MultiPolygon'].includes(feature.geometry?.type)&&['source','verified'].includes(a.mapContext.boundaryStatus)?feature:null;}
 function visiblePoints(withinView=true){const bounds=S.map?.getBounds();let source=Y.loading?[]:(Y.pois||[]).filter(p=>!p.industryId||p.industryId===Y.industry);if(Y.route!=='supply')source=source.filter(p=>!p.archived&&p.status!=='closed');if(Y.route==='supply'){const q=Y.poiQuery.trim().toLocaleLowerCase();source=source.filter(p=>(Y.poiTab==='archived'?p.archived:!p.archived&&(Y.poiTab==='all'||(Y.poiTab==='unverified'?(p.relation==='unverified'||p.status==='pending'):p.relation===Y.poiTab)))&&(!Y.poiArea||poiMatchesArea(p,Y.poiArea))&&(!Y.brandFilter||p.brand===Y.brandFilter)&&(`${branchName(p)} ${p.brand||''} ${areaName(p.area)} ${provinceName(AREA_INDEX.get(p.area)?.province||p.province)}`.toLocaleLowerCase().includes(q)));}return source.filter(p=>{const relation=p.relation==='own'?'own':p.relation==='competitor'?'competitor':'unverified';return validPoint(p)&&S.show[relation]&&(!withinView||!bounds||bounds.contains([p.lat,p.lng]));});}
 function provinceLabel(code,summary){return provinceName(code)+' · '+number(summary?.rows.length||0)+' '+text('ทำเลในมุมมองนี้','locations in this view')+(summary?.bestTier?' · '+text('Tier ยืนยันดีที่สุด ','Best confirmed tier ')+summary.bestTier:' · '+text('ยังไม่มีไข่แดงผ่านยืนยัน','No confirmed qualifying Yolk'))+(summary?.review?' · '+number(summary.review)+' '+text('รอตรวจ','need review'):'');}
 function getNavigation(){return {...S.nav};}
 function areaDistricts(area){const row=S.hierarchy?.areas?.[typeof area==='string'?area:area?.id];return row?.districtIds||(row?.districtId?[row.districtId]:[]);}
 function areaMatchesNavigation(area){const a=typeof area==='string'?AREA_INDEX.get(area):area;if(!a)return false;if(S.nav.level==='location')return a.id===S.nav.areaId;if(S.nav.provinceCode&&String(a.province)!==S.nav.provinceCode)return false;if(S.nav.level==='district'&&!areaDistricts(a).includes(S.nav.districtId))return false;return true;}
 function poiMatchesArea(p,id){if(!p||!id)return false;if(p.area===id)return true;if(p.area)return false;const boundary=usableGeometry(AREA_INDEX.get(id));return !!boundary&&validPoint(p)&&pointInside(boundary,p);}
 function poiMatchesNavigation(p){if(S.nav.level==='country')return true;if(S.nav.level==='location')return !!S.nav.areaId&&poiMatchesArea(p,S.nav.areaId);const a=AREA_INDEX.get(p.area),province=String(p.province||p.adminScope?.province_code||a?.province||'');if(S.nav.provinceCode&&province!==S.nav.provinceCode)return false;if(S.nav.level==='location')return !!S.nav.areaId&&p.area===S.nav.areaId;if(S.nav.level!=='district')return true;if(a)return areaDistricts(a).includes(S.nav.districtId);const sourceId=p.adminScope?.district_id;if(!sourceId)return false;const d=(S.hierarchy?.districts||[]).find(d=>d.provinceCode===province&&(d.id===sourceId||d.sourceId===sourceId));return !!d&&d.id===S.nav.districtId;}
 function navigationLabel(){if(S.nav.level==='location')return S.nav.areaId?areaName(S.nav.areaId):text('พิกัดสาขา · ขอบเขตยังไม่ทราบ','Branch coordinate · boundary unresolved');if(S.nav.level==='district')return S.nav.districtName||S.nav.districtId;if(S.nav.level==='province')return provinceName(S.nav.provinceCode);return text('ทั้งประเทศ','Nationwide');}
 function notifyNavigation(){if(S.callbacks.onNavigate)S.callbacks.onNavigate(getNavigation());else S.callbacks.onProvince?.(S.nav.provinceCode);}
 function fitNavigation(){if(!S.map)return false;let bounds;if(S.nav.level==='country')bounds=S.provinceGroup?.getBounds();else if(S.nav.level==='province')bounds=S.provinceLayers.get(S.nav.provinceCode)?.getBounds();else if(S.nav.level==='district')bounds=S.districtLayers.get(S.nav.districtId)?.getBounds();else if(S.nav.areaId){const a=AREA_INDEX.get(S.nav.areaId),feature=usableGeometry(a);bounds=feature?global.L.geoJSON(feature).getBounds():extentBounds(a?.extent3857);}if(bounds)S.map.fitBounds(bounds,{paddingTopLeft:[18,18],paddingBottomRight:[18,global.innerWidth<1100?Math.max(50,Math.ceil(S.panel?.querySelector('.workspace-map-footer')?.getBoundingClientRect?.().height||0)+18):18],maxZoom:S.nav.level==='location'?16:S.nav.level==='district'?13:11,animate:false});return !!bounds;}
 function navigate(path,{fit=true,notify=true}={}){S.hover?.clear();if(!['country','province','district','location'].includes(path?.level))return false;S.focusTicket++;S.viewInteracted=true;const district=S.districtIndex.get(path.districtId);S.nav={level:path.level,provinceCode:path.level==='country'?'':String(path.provinceCode||district?.provinceCode||''),districtId:['district','location'].includes(path.level)?path.districtId||'':'',districtName:district?.nameTh||path.districtName||'',areaId:path.level==='location'?path.areaId||'':''};S.districtChoices=[];S.focusedArea=S.nav.areaId;S.focusedPoi='';if(fit)fitNavigation();sync();if(notify)notifyNavigation();return true;}
 function back(){const n=S.nav;if(n.level==='location')return navigate(n.districtId?{level:'district',provinceCode:n.provinceCode,districtId:n.districtId,districtName:n.districtName}:n.provinceCode?{level:'province',provinceCode:n.provinceCode}:{level:'country'});if(n.level==='district')return navigate({level:'province',provinceCode:n.provinceCode});return navigate({level:'country'});}
 function focusProvince(code){navigate({level:'province',provinceCode:String(code)});}
 async function loadHierarchy(){if(S.hierarchyPromise)return S.hierarchyPromise;if(S.hierarchy&&S.districtData)return;S.hierarchyPromise=(async()=>{try{const responses=await Promise.all([fetch('data/real/hierarchy-index.json',{cache:'no-store'}),fetch('data/real/district-boundaries.geojson',{cache:'no-store'})]);if(responses.some(r=>!r.ok))throw Error('Hierarchy source unavailable');const [index,geometry]=await Promise.all(responses.map(r=>r.json()));if(!Array.isArray(index.districts)||!index.areas||!Array.isArray(geometry.features))throw Error('Invalid hierarchy source');S.hierarchy=index;S.districtIndex=new Map(index.districts.map(d=>[d.id,d]));S.districtData=geometry;S.hierarchyError='';sync();}catch(error){S.hierarchyError=text('ขอบเขตอำเภอและการเชื่อมทำเลยังไม่พร้อม แสดงเฉพาะเส้นจังหวัด ไม่ใช้สีจังหวัดแทน','District boundaries and location crosswalk are unavailable. Province outlines remain; province colouring is not substituted.')+' '+String(error.message);setMessage(S.hierarchyError);}finally{S.hierarchyPromise=null;sync();}})();return S.hierarchyPromise;}
 async function loadFine(province){if(!province||!S.hierarchy)return;if(S.fineCache.has(province)||S.finePending.has(province)||S.fineErrors.has(province))return S.finePending.get(province);const configured=S.hierarchy.fineFiles?.[province],file=(typeof configured==='string'?configured:configured?.file)||Object.values(S.hierarchy.areas).find(a=>a.provinceCode===province&&a.geometryFile)?.geometryFile;if(!file){S.fineCache.set(province,{type:'FeatureCollection',features:[]});return;}if(!/^data\/real\/[A-Za-z0-9_./-]+\.geojson$/.test(file)||file.includes('..')){S.fineErrors.set(province,'Invalid local geometry file');return;}const promise=(async()=>{try{const response=await fetch(file,{cache:'no-store'});if(!response.ok)throw Error('Fine boundaries HTTP '+response.status);const data=await response.json();if(!Array.isArray(data.features))throw Error('Invalid fine boundaries');for(const feature of data.features){const id=feature.properties?.areaId||feature.id,a=AREA_INDEX.get(id);if(a&&['Polygon','MultiPolygon'].includes(feature.geometry?.type)){a.mapContext.boundary=feature;a.mapContext.boundaryStatus='source';}}S.fineCache.set(province,data);S.fineErrors.delete(province);sync();}catch(error){S.fineErrors.set(province,String(error.message));sync();}finally{S.finePending.delete(province);sync();}})();S.finePending.set(province,promise);return promise;}
 async function loadProvinces(){
  if(S.provinceData||S.provincePromise)return S.provincePromise;
  S.provincePromise=(async()=>{try{const response=await fetch('data/real/province-boundaries.geojson',{cache:'no-store'});if(!response.ok)throw Error('Province boundaries HTTP '+response.status);const data=await response.json();const features=data.features||[],codes=features.map(f=>String(f.properties?.code||''));if(features.length!==77||new Set(codes).size!==77||codes.some(c=>!/^\d{2}$/.test(c)))throw Error('Expected 77 unique province codes');S.provinceData=data;S.provinceError='';
   S.provinceGroup=global.L.geoJSON(data,{style:{weight:1,opacity:1,fill:false,fillOpacity:1,color:value('--yl-border-strong'),fillColor:value('--no-result')},onEachFeature(feature,layer){const code=String(feature.properties.code);S.provinceLayers.set(code,layer);layer.on('click',()=>{if(S.nav.level==='country')focusProvince(code);});layer.on('add',()=>{const element=layer.getElement?.();if(element){element.setAttribute('tabindex','0');element.setAttribute('role','button');element.addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();if(S.nav.level==='country')focusProvince(code);}});}});}}).addTo(S.map);S.provinceGroup.bringToBack?.();sync();
  }catch(error){S.provinceError=text('โหลดขอบเขตจังหวัดไม่ได้ · จุดและทำเลที่มีข้อมูลยังดูได้','Province boundaries unavailable. Available places and pins remain usable.')+' '+String(error.message);setMessage(S.provinceError);}finally{S.provincePromise=null;}})();return S.provincePromise;
 }
 function setMessage(message){const output=S.panel?.querySelector('[data-workspace-map-status]');if(output)output.textContent=message||'';}
 function setControlsOpen(open){S.controlsOpen=!!open;S.panel.dataset.workspaceControlsOpen=String(S.controlsOpen);const button=S.panel.querySelector('[data-workspace-controls-toggle]');if(button)button.setAttribute('aria-expanded',String(S.controlsOpen));}
 function updateLanguage(){const toggle=S.panel.querySelector('[data-workspace-controls-toggle]');if(toggle){toggle.setAttribute('aria-label',text('ตั้งค่าแผนที่','Map options'));toggle.setAttribute('aria-expanded',String(S.controlsOpen));const label=toggle.querySelector('[data-workspace-controls-label]');if(label)label.textContent=text('ตั้งค่าแผนที่','Map options');}const viewSelect=S.panel.querySelector('[data-workspace-map-layer]');if(viewSelect)viewSelect.setAttribute('aria-label',text('มุมมองแผนที่','Map view'));const basemap=S.panel.querySelector('[data-workspace-basemap]');if(basemap)basemap.setAttribute('aria-label',text('แผนที่พื้นหลัง','Basemap'));if(basemap)for(const option of basemap.options||[])option.textContent=text(...({simplified:['เรียบง่าย','Simplified'],satellite:['ดาวเทียม','Satellite'],detailed:['รายละเอียด','Detailed']}[option.value]));const label=S.panel.querySelector('[data-workspace-basemap-label]');if(label)label.textContent=text('แผนที่พื้นหลัง','Basemap');const evidence=S.panel.querySelector('[data-workspace-map-evidence-label]');if(evidence){evidence.setAttribute('aria-label',text('พิกัดและขอบเขตที่แสดง','Coordinates & boundaries shown'));evidence.innerHTML=`<span class="workspace-map-evidence-full">${text('พิกัดและขอบเขตที่แสดง','Coordinates & boundaries shown')}</span><span class="workspace-map-evidence-compact" aria-hidden="true">${icon('info')}</span>`;}S.panel.querySelector('[data-workspace-poi-layers]')?.setAttribute('aria-label',text('ชั้นข้อมูลสาขา','Branch layers'));S.host.setAttribute('aria-label',text('แผนที่โต้ตอบ เลื่อนและซูมเพื่อสำรวจทำเล','Interactive map. Pan and zoom to explore locations'));for(const [selector,th,en]of [['.leaflet-control-zoom-in','ซูมเข้า','Zoom in'],['.leaflet-control-zoom-out','ซูมออก','Zoom out']]){const button=S.panel.querySelector(selector);if(button){button.setAttribute('title',text(th,en));button.setAttribute('aria-label',text(th,en));}}}
 function updateCounts(pointsShown,pointsTotal,areasShown,areaTotal){
  const counts=S.panel.querySelector('[data-workspace-map-counts]');counts.textContent=(pointsTotal?`${text('หมุด','Pins')} ${number(pointsShown)}/${number(pointsTotal)} ${text('รายการในกรอบแผนที่','within view')}${pointsTotal>MAX_POINTS?' · '+text('จำกัด 1,000 หมุด · ซูมเข้าเพื่อดูเพิ่ม','1,000-pin limit; zoom in for more'):''} · `:'')+(areaTotal?`${text('Polygon ทำเล','Location polygons')} ${number(areasShown)}/${number(areaTotal)} · ${text('ยังไม่มี Polygon','No polygon')} ${number(Math.max(0,areaTotal-areasShown))} · `:'')+text('เส้นประ = กรอบพิกัดต้นทาง ใช้จัดมุมมอง ไม่ใช่ขอบเขตทำเล · Polygon มีเฉพาะที่ต้นทางให้มา','Dashed rectangles = source extents, not location boundaries. Polygons exist only where retrieved from source.');
 }
 function updateChrome(s,rows,pointsShown,pointsTotal,areasShown,areaTotal){
  const crumbs=S.panel.querySelector('[data-workspace-map-breadcrumbs]');if(crumbs){const parts=[['country',text('ประเทศ','Country')]];if(S.nav.provinceCode)parts.push(['province',provinceName(S.nav.provinceCode)]);if(S.nav.districtId)parts.push(['district',S.nav.districtName||S.nav.districtId]);if(S.nav.level==='location')parts.push(['location',navigationLabel()]);crumbs.innerHTML=parts.map(([level,label],i)=>i===parts.length-1?`<strong aria-current="location">${esc(label)}</strong>`:`<button type="button" data-workspace-nav-level="${level}">${esc(label)}</button>`).join('<span aria-hidden="true">›</span>')+`<span class="workspace-map-grain">· ${text(S.nav.level==='country'?'สีระดับอำเภอ':'สีระดับแขวง/อปท.',S.nav.level==='country'?'District colours':'Khwaeng / local-authority colours')}</span>`;}S.panel.querySelector('[data-workspace-map-back]')?.setAttribute('aria-label',text('กลับระดับก่อนหน้า','Back one level'));if(S.panel.querySelector('[data-workspace-map-back]'))S.panel.querySelector('[data-workspace-map-back]').hidden=S.nav.level==='country';const choices=S.panel.querySelector('[data-workspace-district-choices]');if(choices){choices.hidden=!S.districtChoices.length;choices.innerHTML=S.districtChoices.map(id=>`<button type="button" data-workspace-district-choice="${esc(id)}">${esc(S.districtIndex.get(id)?.nameTh||id)}</button>`).join('');}const poiControls=S.panel.querySelector('[data-workspace-poi-layers]');if(poiControls)poiControls.hidden=S.nav.level!=='location'&&Y.route!=='poi';
  const title=S.panel.querySelector('[data-workspace-map-title]');title.innerHTML=`<span class="workspace-map-title-full">${esc(Y.route==='criteria'?text('ปรับเกณฑ์ ดูไข่แดงเปลี่ยน','Tune criteria. See your Yolks change.'):text('ไข่แดงและช่องว่างสาขา','Yolks and branch gaps'))}</span><span class="workspace-map-title-compact">${esc(Y.route==='criteria'?text('ลองเกณฑ์ · Yolk','Tune criteria · Yolk'):text('ไข่แดง · Yolk','Yolk map'))}</span>`;
  const mode=S.panel.querySelector('[data-workspace-map-layer]');for(const option of mode.options||[])option.textContent=text(...layerLabels[option.value]);mode.value=S.layer;
  S.panel.querySelector('[data-workspace-map-home]').setAttribute('aria-label',text('ดูทั้งประเทศ','Show nationwide'));
  const scoped={next:s.next.filter(areaMatchesNavigation),added:s.added.filter(areaMatchesNavigation),removed:s.removed.filter(areaMatchesNavigation),moved:s.moved.filter(areaMatchesNavigation)};const stats=S.panel.querySelector('[data-workspace-map-stats]'),statsLabel=(full,compact)=>`<span class="workspace-map-stats-label">${esc(full)}</span><span class="workspace-map-stats-compact">${esc(compact)}</span>`;stats.innerHTML=Y.route==='criteria'?`<strong>${number(scoped.next.length)}</strong> ${statsLabel(text('ทำเลผ่านแบบร่าง','draft matches'),text('ผ่าน','match'))} <span>+${number(scoped.added.length)} / −${number(scoped.removed.length)}</span> <span>↕ ${number(scoped.moved.length)}<span class="workspace-map-stats-label"> ${text('อันดับเปลี่ยน','ranks changed')}</span></span>`:`<strong>${number(rows.length)}</strong> ${statsLabel(text(Y.route==='targets'?'ทำเลที่เล็งไว้':Y.route==='feed'||Y.route==='inbox'?'ทำเลในประวัติ':'ทำเลในมุมมองนี้',Y.route==='targets'?'saved locations':Y.route==='feed'||Y.route==='inbox'?'locations in activity':'locations in this view'),text(Y.route==='targets'?'เล็งไว้':Y.route==='feed'||Y.route==='inbox'?'ในประวัติ':'ทำเล',Y.route==='targets'?'saved':Y.route==='feed'||Y.route==='inbox'?'in activity':'locations'))}`;
  const legend=S.panel.querySelector('[data-workspace-map-legend]'),selected=S.nav.level==='location'?(rows.find(a=>a.id===S.nav.areaId)||s.nextRows.find(a=>a.id===S.nav.areaId)):null;legend.innerHTML=(S.nav.level==='location'?`<span><i class="workspace-selected-outline"></i>${text('ด้านในโปร่งใส · เส้นขอบคือทำเลที่เลือก','Transparent interior · outline marks selected location')}</span>${selected?`<span>${selected.qualifyingTier?'Tier '+selected.qualifyingTier+' · ':''}${text(selected.demand===true?'Demand สูง':selected.demand===null?'Demand รอตรวจ':'Demand ยังไม่ผ่าน',selected.demand===true?'High Demand':selected.demand===null?'Demand unresolved':'Demand below criteria')}</span>`:''}`:[3,2,1].map(t=>`<span><i class="yolk-tier-swatch" data-yolk-tier="${t}"></i>${esc((Y.lang==='en'?global.YolkTierStyle?.definition(t)?.labelEn:global.YolkTierStyle?.definition(t)?.labelTh)||'Tier '+t)}</span>`).join('')+`<span><i class="workspace-neutral"></i><span class="workspace-map-legend-full">${text('ยังไม่ผ่านยืนยัน','No confirmed match')}</span><span class="workspace-map-legend-compact">${text('ยังไม่ผ่าน','No match')}</span></span><span> ? <span class="workspace-map-legend-full">${text('ข้อมูลรอตรวจแยกต่างหาก','Unresolved evidence is separate')}</span><span class="workspace-map-legend-compact">${text('รอตรวจ','Review')}</span></span>`)+(S.draftVisible?`<span>D · ${text('พิกัดแบบร่าง ยังไม่นับสาขา','Draft coordinate, excluded from supply')}</span>`:'');
  const note=S.panel.querySelector('[data-workspace-map-note]');note.textContent=S.nav.level==='country'?text('สีรายอำเภอ = Tier ยืนยันดีที่สุดของทำเลที่ผ่านในอำเภอนั้น · กดเพื่อเลือกจังหวัด','District colour = best confirmed tier of qualifying source locations. Select to enter a province.'):text('สีรายทำเล = Tier ที่ผ่านยืนยันของแขวง/อปท. · ประเทศ → จังหวัด → อำเภอ → ทำเล → สาขา','Location colour = confirmed qualifying tier of a source Khwaeng/local-authority polygon. Country → province → district → location → stores.');
  updateCounts(pointsShown,pointsTotal,areasShown,areaTotal);
  const layerLabel=S.panel.querySelector('[data-workspace-layer-label]');layerLabel.textContent=text('มุมมองแผนที่','Map view');
  S.panel.querySelector('[data-workspace-map-focus]').hidden=!S.focusedArea&&!S.focusedPoi;
  S.panel.querySelector('[data-workspace-map-focus]').textContent=text('กลับจุดที่เลือก','Fit selection');
  for(const button of S.panel.querySelectorAll('[data-workspace-poi-layer]')){button.setAttribute('aria-pressed',String(S.show[button.dataset.workspacePoiLayer]));const label=button.querySelector('span');if(label)label.textContent=text(...({own:['เรา','Our stores'],competitor:['คู่แข่ง','Competitors'],unverified:['รอตรวจ','To verify']}[button.dataset.workspacePoiLayer]));}
 }
 function analyticalLegend(p){
  const rows=p?.legend||[];
  if(rows.length===41){const format=v=>Number.isFinite(v)?new Intl.NumberFormat(Y.lang==='en'?'en-US':'th-TH',{maximumSignificantDigits:3}).format(v):'—';return `<div class="workspace-lut-legend"><div class="workspace-lut-bar" role="img" aria-label="${esc(text('สเกลสี DS 41 ช่วง','DS scale, 41 colour steps'))}">${rows.map(x=>`<i style="background:${x.color}" title="${esc(text(x.labelTh,x.labelEn)+' '+text(x.unitTh,x.unitEn))}"></i>`).join('')}</div><div class="workspace-lut-labels">${[0,10,20,30,40].map(i=>`<span>${i===40?'≥ ':''}${format(rows[i]?.lower)}</span>`).join('')}</div><small>${text('41 ช่วง · เทียบทั้งประเทศ · ศูนย์ที่ทราบมีเส้นประกำกับ','41 steps · national comparison · known zero is dashed')}</small></div>`;}
  return rows.map(x=>`<span><i class="yolk-tier-swatch" style="background:${x.css||x.color}"></i>${esc(text(x.labelTh,x.labelEn))}</span>`).join('');
 }
 function updateAnalysisChrome(s,rows){
  const mode=S.panel.querySelector('[data-workspace-map-layer]'),caption=S.panel.querySelector('[data-workspace-analysis-caption]');if(mode?.parentElement)mode.parentElement.hidden=!!S.analysis;
  if(!S.analysis){delete S.panel.dataset.analysisKind;if(caption)caption.textContent='';return;}
  S.panel.dataset.analysisKind=S.analysis.kind;const supply=S.analysis.kind==='supply',country=S.nav.level==='country',p=supply&&country?S.analysisDistrict:S.analysisFine,meta=p?.metadata;
  const title=S.panel.querySelector('[data-workspace-map-title]');title.innerHTML=`<span class="workspace-map-title-full">${supply?text('Supply · สาขากระจุกตรงไหน','Supply · Where are the branches?'):text('Demand · ไข่แดงอยู่ที่ไหน','Demand · Where are the Yolks?')}</span><span class="workspace-map-title-compact">${supply?text('Supply · สาขา','Supply · Branches'):text('Demand · ไข่แดง','Demand · Yolks')}</span>`;
  const records=supply&&country?[...(p?.records.values()||[])]:rows.map(a=>p?.records.get(a.id)).filter(Boolean),known=records.filter(r=>r.state==='known'),review=records.filter(r=>r.state==='review');
  S.panel.querySelector('[data-workspace-map-stats]').innerHTML=supply?`<strong>${number(known.length)}</strong> ${text(country?'อำเภอมีข้อมูล':'ทำเลมีข้อมูล',country?'districts with data':'locations with data')} · ? ${number(review.length)} ${text('รอตรวจ','review')}`:S.analysis.metric==='tier'?`<strong>${number(rows.filter(a=>a.demand===true).length)}</strong> ${text('ไข่แดงจาก Demand','Demand Yolks')} · ? ${number(rows.filter(a=>a.demand===null).length)}`:`<strong>${number(known.length)}</strong> ${text('ทำเลมีข้อมูลตัววัดนี้','locations with this signal')} · ? ${number(rows.length-known.length)} ${text('ไม่มีข้อมูล / รอตรวจ','no data / review')}`;
  if(caption)caption.textContent=meta?(supply?({own:'O',competitor:'C',total:'O+C'}[S.analysis.relation])+' · '+text(meta.unitTh,meta.unitEn)+(meta.denominatorId==='gfa'?text(' · GFA ประมาณ',' · estimated GFA'):''):S.analysis.metric==='tier'?text('สัญญาณ Demand · Tier 1–3','Demand proxy · Tier 1–3'):text(meta.unitTh,meta.unitEn)+' · '+text(meta.metricLabelTh,meta.metricLabelEn)):text('กำลังอ่านยอดสาขาระดับอำเภอ','Loading native district totals');
  const selected=S.nav.level==='location'?S.analysisFine?.records.get(S.nav.areaId):null,legend=S.panel.querySelector('[data-workspace-map-legend]');
  if(S.nav.level==='location')legend.innerHTML=`<span><i class="workspace-selected-outline"></i>${text('ขอบเขตที่เลือก · ด้านในโปร่งใส','Selected outline · transparent interior')}</span><span>${esc(analysisRecordLabel(selected))}</span>`;
  else legend.innerHTML=analyticalLegend(p)+`<span><i class="workspace-neutral"></i>${text(supply||S.analysis.metric!=='tier'?'ไม่มีข้อมูล / รอตรวจ':'ยังไม่เป็นไข่แดง / ไม่มีข้อมูล / รอตรวจ',supply||S.analysis.metric!=='tier'?'No data / review':'Below Yolk / no data / review')}</span>`;
  const count=supply&&country?S.nativeDistrictCache.get(Y.industry)?.metadata:null;
  S.panel.querySelector('[data-workspace-map-note]').textContent=(supply?country?text('ยอดสาขาระดับอำเภอจากต้นทางโดยตรง ไม่บวกจาก อปท.','Direct native district totals, not sums of local-authority counts'):text('ยอดต้นทางรายแขวง/อปท. ตาม format ที่เลือก ไม่รวมการแก้ POI ของทีมที่ยังไม่กระทบยอด','Source totals per Khwaeng/local authority for the selected format; unreconciled team edits stay separate'):country?text(S.analysis.metric==='tier'?'สีอำเภอ = Tier ไข่แดงดีที่สุดในทำเลที่สัมพันธ์กับอำเภอ':'สีอำเภอ = ค่าสูงสุดของทำเลที่สัมพันธ์กับอำเภอ ไม่ใช่ยอดรวมอำเภอ',S.analysis.metric==='tier'?'District colour = best confirmed Yolk tier among related fine locations':'District colour = maximum related fine-location value, not a district aggregate'):text('ข้อมูลรายแขวง/อปท. ไม่กรองตาม Supply หรือรูปแบบทำเล','Fine-area signals before Supply and preferred-pattern filtering'))+(p&&S.analysis.metric!=='tier'?' · '+text('ช่วงสี 41 ฐานทั่วประเทศระดับเดียวกัน','41 colour steps across the national same-grain cohort')+' · n='+number(p.cohort.exact):'')+(count?' · '+text('ดึงข้อมูล ','Retrieved ')+String(count.sourceRetrievedTo||'').slice(0,10):'');
 }
 function summaryByDistrict(rows,allRows){const result=new Map();for(const d of S.hierarchy?.districts||[])result.set(d.id,{rows:[],bestTier:null,review:0});for(const a of rows)for(const id of areaDistricts(a)){const item=result.get(id);if(!item)continue;item.rows.push(a);if(a.eligible&&a.demand===true&&tierClass(a.qualifyingTier))item.bestTier=item.bestTier===null?a.qualifyingTier:Math.min(item.bestTier,a.qualifyingTier);}for(const a of allRows)if(a.reviewCandidate||a.demand===null)for(const id of areaDistricts(a)){const item=result.get(id);if(item)item.review++;}return result;}
 function accessibleLayer(layer,label,action){layer.bindTooltip(esc(label),{sticky:true});layer.on('click',action);layer.on('add',()=>{const element=layer.getElement?.();if(element){element.setAttribute('tabindex','0');element.setAttribute('role','button');element.setAttribute('aria-label',layer.yolkAccessibleLabel||label);if(S.keyboardElements.has(element))return;S.keyboardElements.add(element);element.addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();action();}});}});}
 function drawDistricts(rows,s){S.districtGroup.clearLayers();if(!S.districtData)return;const summaries=summaryByDistrict(rows,s.nextRows),moved=Y.route==='criteria'?summaryByDistrict(s.moved,[]):null;for(const feature of S.districtData.features){const id=feature.properties.id||feature.id,d=S.districtIndex.get(id);if(!d)continue;let record=S.districtRecords.get(id);if(!record){const children=[];const group=global.L.geoJSON(feature,{onEachFeature(f,layer){children.push(layer);accessibleLayer(layer,'',()=>S.nav.level==='country'?navigate({level:'province',provinceCode:d.provinceCode}):navigate({level:'district',provinceCode:d.provinceCode,districtId:id,districtName:d.nameTh}));}});record={group,children};S.districtRecords.set(id,record);S.districtLayers.set(id,group);}if(S.nav.provinceCode&&d.provinceCode!==S.nav.provinceCode)continue;if(S.nav.level==='location')continue;const summary=summaries.get(id),fill=S.nav.level==='country',analytical=S.analysis?(S.analysis.kind==='supply'?S.analysisDistrict?.records.get(id):districtDemandRecord(id)):null;record.group.setStyle({color:value('--yl-border-strong'),weight:S.nav.districtId===id?2.5:1,fill,fillColor:S.analysis?(analytical?.paint||analytical?.color||value('--no-result')):tierColor(summary?.bestTier),fillOpacity:1,opacity:1,dashArray:S.analysis?analytical?.state==='review'||!analytical?'6 4':analytical?.zero?'2 2':null:summary?.review&&!summary?.bestTier?'6 4':null});const label=S.analysis?(d.nameTh||id)+' · '+global.YolkAnalysisUI.metricLabel(S.analysis)+' · '+analysisRecordLabel(analytical)+(S.analysis.kind==='demand'?' · '+text(S.analysis.metric==='tier'?'Tier ไข่แดงดีที่สุดของทำเลในอำเภอ':'ค่าสูงสุดของทำเลในอำเภอ',S.analysis.metric==='tier'?'Best Yolk tier among district locations':'Maximum fine-location value in district'):' · '+text('ยอดต้นทางระดับอำเภอ','Native district source totals')):(d.nameTh||id)+' · '+number(summary?.rows.length||0)+' '+text('ทำเลที่ขอบเขตสัมพันธ์กับอำเภอในมุมมองนี้','source locations related to this district in view')+(summary?.bestTier?' · Tier '+summary.bestTier:' · '+text('ยังไม่ผ่านยืนยัน','No confirmed match'))+(summary?.review?' · '+number(summary.review)+' '+text('รอตรวจ','needs review'):'')+(moved?.get(id)?.rows.length?' · ↕ '+number(moved.get(id).rows.length)+' '+text('อันดับเปลี่ยน','ranks changed'):'');for(const layer of record.children){layer.yolkAccessibleLabel=label;layer.unbindTooltip?.();layer.bindTooltip(esc(label),{sticky:true});layer.getElement?.()?.setAttribute('aria-label',label);}record.group.addTo(S.districtGroup);}return summaries;}
 function drawAreas(rows,s){S.areaGroup.clearLayers();if(S.nav.level==='country')return {shown:0,total:0,available:0};const rowsById=new Map(rows.map(a=>[a.id,a])),all=s.nextRows.filter(areaMatchesNavigation),focused=S.nav.areaId;
  let candidates=all.filter(a=>usableGeometry(a));if(focused)candidates.sort((a,b)=>Number(b.id===focused)-Number(a.id===focused));let shown=0;for(const a of candidates.slice(0,MAX_AREAS)){const boundary=usableGeometry(a),paint=rowsById.get(a.id),state=paint||a,active=!!paint&&paint.eligible&&paint.demand===true,selected=a.id===focused,ids=areaDistricts(a);let record=S.areaRecords.get(a.id);if(!record||record.boundary!==boundary){const children=[];const group=global.L.geoJSON(boundary,{onEachFeature(feature,layer){children.push(layer);S.hover?.bind(layer,()=>S.nav.level==='district'?{level:'location',id:a.id,feature:boundary,label:areaName(a.id)}:null);accessibleLayer(layer,'',()=>{const current=AREA_INDEX.get(a.id),districtIds=areaDistricts(current);if(S.nav.level==='province'){if(districtIds.length===1)navigate({level:'district',provinceCode:a.province,districtId:districtIds[0]});else{S.districtChoices=districtIds;sync();setMessage(districtIds.length?text('ทำเลนี้สัมพันธ์กับหลายอำเภอ เลือกอำเภอที่จะเจาะต่อ','This location relates to multiple districts. Choose a district to explore.'):text('ทำเลนี้ยังเชื่อมอำเภอไม่ได้แน่ชัด กรุณาตรวจข้อมูลก่อน','This location has unresolved district mapping. Review the source crosswalk first.'));}}else{navigate({level:'location',provinceCode:a.province,districtId:districtIds.length===1?districtIds[0]:S.nav.districtId,areaId:a.id});if(!['demand','supply'].includes(Y.route))S.callbacks.onArea?.(a.id);}});}});record={group,children,boundary};S.areaRecords.set(a.id,record);}const analytical=S.analysisFine?.records.get(a.id),color=S.analysis?(analytical?.paint||analytical?.color||value('--no-result')):active?tierColor(state.qualifyingTier):value('--no-result');record.group.setStyle({color:selected?value('--yl-map-active'):value('--yl-border-strong'),weight:selected?3:1,fill:S.nav.level!=='location'&&!selected,fillColor:color,fillOpacity:1,opacity:1,dashArray:S.analysis?analytical?.state!=='known'?'5 4':analytical?.zero?'2 2':null:state.reviewCandidate&&!active?'5 4':null});const changedRank=s.oldRanks.has(a.id)&&s.nextRanks.has(a.id)&&s.oldRanks.get(a.id)!==s.nextRanks.get(a.id);const label=S.analysis?areaName(a.id)+' · '+global.YolkAnalysisUI.metricLabel(S.analysis)+' · '+analysisRecordLabel(analytical):areaName(a.id)+' · '+text('Polygon ต้นทาง CityMETER','CityMETER source polygon')+(active?' · Tier '+state.qualifyingTier:' · '+text('ยังไม่ผ่านยืนยัน','No confirmed match'))+(Y.route==='criteria'&&changedRank?' · ↕ '+s.oldRanks.get(a.id)+' → '+s.nextRanks.get(a.id):'');for(const layer of record.children){layer.yolkAccessibleLabel=label;layer.unbindTooltip?.();layer.bindTooltip(esc(label),{sticky:true});layer.getElement?.()?.setAttribute('aria-label',label);}record.group.addTo(S.areaGroup);shown++;}
  if(focused&&!candidates.some(a=>a.id===focused)){const a=AREA_INDEX.get(focused),extent=extentBounds(a?.extent3857);if(extent)global.L.rectangle(extent,{color:value('--yl-map-active'),weight:2,opacity:1,fill:false,dashArray:'6 5'}).bindTooltip(esc(text('กรอบพิกัดต้นทาง ไม่ใช่ขอบเขตหรือ Choropleth','Source extent, not a boundary or choropleth'))).addTo(S.areaGroup);}
  return {shown,total:all.length,available:candidates.length};
 }
 const boundaryExtentCache=new WeakMap();
 function pointInside(feature,p){if(!feature?.geometry)return false;let extent=boundaryExtentCache.get(feature.geometry);if(!extent){extent=[Infinity,Infinity,-Infinity,-Infinity];const visit=part=>{if(typeof part[0]==='number'){extent[0]=Math.min(extent[0],part[0]);extent[1]=Math.min(extent[1],part[1]);extent[2]=Math.max(extent[2],part[0]);extent[3]=Math.max(extent[3],part[1]);}else for(const child of part)visit(child);};visit(feature.geometry.coordinates);boundaryExtentCache.set(feature.geometry,extent);}if(p.lng<extent[0]||p.lng>extent[2]||p.lat<extent[1]||p.lat>extent[3])return false;const inRing=ring=>{let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [xi,yi]=ring[i],[xj,yj]=ring[j];if((yi>p.lat)!==(yj>p.lat)&&p.lng<(xj-xi)*(p.lat-yi)/(yj-yi)+xi)inside=!inside;}return inside;};const polygon=poly=>inRing(poly[0])&&!poly.slice(1).some(inRing);return feature.geometry.type==='Polygon'?polygon(feature.geometry.coordinates):feature.geometry.type==='MultiPolygon'?feature.geometry.coordinates.some(polygon):false;}
 function clearPoints(){S.pointGroup.clearLayers();S.pointRecords.clear();S.pointContext='';if(S.panel)S.panel.dataset.workspacePopupOpen='false';}
 function legacyPointPopup(p,relation,symbol,title){return `<strong>${esc(title)}</strong><p>${symbol} · ${esc(text(...({own:['สาขาเรา','Our stores'],competitor:['คู่แข่ง','Competitors'],unverified:['รอตรวจสอบ','To verify']}[relation])))}</p><p>${esc(text('พิกัดรายการต้นทางหรือทีมบันทึก ไม่ยืนยันการเปิดบริการหรือเขตพื้นที่','Source or team coordinates; neither current operation nor boundary membership is certified.'))}</p><button type="button" data-workspace-open-poi="${esc(p.id)}">${esc(text('ดูข้อมูลสาขา','View branch'))}</button>`;}
 function drawPoints(){
  const context=criteriaContextKey();if(S.pointContext!==context){clearPoints();S.pointContext=context;}
  const showPoints=S.nav.level==='location'||Y.route==='poi',valid=showPoints?visiblePoints():[];let candidates=valid;if(S.nav.areaId){candidates=valid.filter(p=>p.id===S.focusedPoi||poiMatchesArea(p,S.nav.areaId));}else if(S.nav.level==='location')candidates=valid.filter(p=>p.id===S.focusedPoi);else if(Y.route==='poi')candidates=valid.filter(p=>p.id===S.focusedPoi);
  if(['feed','inbox'].includes(Y.route)){const ids=new Set(Y.events.filter(e=>!e.meta?.industry||e.meta.industry===Y.industry).filter(e=>e.entity==='supply').map(e=>e.entity_id));candidates=candidates.filter(p=>ids.has(p.id));}
  const wanted=candidates.slice(0,MAX_POINTS),ids=new Set(wanted.map(p=>p.id));let resetGroup=false;
  for(const [id,record]of S.pointRecords)if(!ids.has(id)){
   // Opening a mobile popup resizes/autopans the map. Retain its anchor while open,
   // but only if it still belongs to this route, visible relationship and source scope.
   if(showPoints&&record.marker.isPopupOpen?.()){const p=visiblePoints(false).find(p=>p.id===id),allowed=p&&(S.nav.areaId?(p.id===S.focusedPoi||poiMatchesArea(p,S.nav.areaId)):p.id===S.focusedPoi)&&(!['feed','inbox'].includes(Y.route)||Y.events.some(e=>(!e.meta?.industry||e.meta.industry===Y.industry)&&e.entity==='supply'&&e.entity_id===id));if(allowed)continue;}
   if(typeof S.pointGroup.removeLayer==='function')S.pointGroup.removeLayer(record.marker);else resetGroup=true;S.pointRecords.delete(id);}
  // Adapter fallback only; native Leaflet removes individual layers and keeps open popups.
  if(resetGroup){S.pointGroup.clearLayers();for(const record of S.pointRecords.values())record.active=false;}
  for(const p of wanted){const relation=p.relation==='own'?'own':p.relation==='competitor'?'competitor':'unverified',symbol={own:'O',competitor:'C',unverified:'U'}[relation],title=branchName(p),signature=JSON.stringify([Y.lang,S.nav.areaId,p]);let record=S.pointRecords.get(p.id);
   if(!record){const marker=global.L.marker([p.lat,p.lng],{keyboard:true,title,alt:title,icon:global.L.divIcon({className:'workspace-poi-marker',html:`<span class="workspace-pin workspace-pin-${relation}" aria-hidden="true">${symbol}</span>`,iconSize:[32,32],iconAnchor:[16,16]})});marker.on('click',()=>{S.focusedPoi=p.id;S.focusedArea='';});record={marker,active:false,signature:'',relation,lat:p.lat,lng:p.lng};S.pointRecords.set(p.id,record);}
   if(record.signature!==signature){if(record.lat!==p.lat||record.lng!==p.lng)record.marker.setLatLng?.([p.lat,p.lng]);if(record.relation!==relation)record.marker.setIcon?.(global.L.divIcon({className:'workspace-poi-marker',html:`<span class="workspace-pin workspace-pin-${relation}" aria-hidden="true">${symbol}</span>`,iconSize:[32,32],iconAnchor:[16,16]}));record.marker.bindTooltip(esc(title));const locationId=p.area||S.nav.areaId,area=locationId?{nameTh:areaName(locationId),nameEn:areaName(locationId),provinceNameTh:provinceName(p.province),provinceNameEn:provinceName(p.province)}:{provinceNameTh:provinceName(p.province),provinceNameEn:provinceName(p.province)};const popup=global.YolkPoiPopup?.render?global.YolkPoiPopup.render(p,{lang:Y.lang,industry:Y.industry,ownBrandId:Y.ownBrandId,ownBrandName:ownBrandName(),area}):legacyPointPopup(p,relation,symbol,title);const openPopup=record.marker.getPopup?.();if(openPopup)openPopup.setContent(popup);else record.marker.bindPopup(popup,{maxWidth:360,minWidth:220});const element=record.marker.getElement?.();if(element){element.setAttribute('title',title);element.setAttribute('aria-label',title);}Object.assign(record,{signature,relation,lat:p.lat,lng:p.lng});}
   if(!record.active){record.marker.addTo(S.pointGroup);record.active=true;}
  }
 return {shown:Math.min(candidates.length,MAX_POINTS),total:candidates.length};
 }
 function drawDraftPoint(){
  S.draftGroup.clearLayers();S.draftVisible=false;if(Y.route!=='poi')return;const form=global.document.getElementById('poi-form'),lat=form?.elements?.lat?.value,lng=form?.elements?.lng?.value;if(typeof lat!=='string'||typeof lng!=='string'||!lat.trim()||!lng.trim())return;const p={lat:Number(lat),lng:Number(lng)};if(!validPoint(p))return;const saved=(Y.pois||[]).find(p=>p.id===form.dataset.id);if(saved&&saved.lat===p.lat&&saved.lng===p.lng)return;
  S.draftVisible=true;const title=text('พิกัดแบบร่าง ยังไม่บันทึกและไม่นับ Supply','Draft coordinates, unsaved and excluded from supply');global.L.marker([p.lat,p.lng],{keyboard:true,title,alt:title,icon:global.L.divIcon({className:'workspace-poi-marker',html:'<span class="workspace-pin workspace-pin-draft" aria-hidden="true">D</span>',iconSize:[32,32],iconAnchor:[16,16]})}).bindTooltip(esc(title)).addTo(S.draftGroup);
 }
 function drawNavigationTargets(){
  if(!S.navigationHitGroup)return;S.hover?.clear();S.navigationHitGroup.clearLayers();
  const country=S.nav.level==='country',province=S.nav.level==='province';if(!country&&!province)return;
  const features=country?S.provinceData?.features:S.districtData?.features;if(!features)return;
  for(const feature of features){const id=String(country?feature.properties.code:feature.properties.id||feature.id),district=country?null:S.districtIndex.get(id);if(!country&&(!district||district.provinceCode!==S.nav.provinceCode))continue;
   const key=(country?'province:':'district:')+id;let record=S.navigationRecords.get(key);
   if(!record){const children=[],group=global.L.geoJSON(feature,{style:{stroke:false,fill:false,interactive:true,className:'workspace-navigation-hit'},onEachFeature(f,layer){children.push(layer);const label=country?provinceName(id):district.nameTh,action=()=>navigate(country?{level:'province',provinceCode:id}:{level:'district',provinceCode:district.provinceCode,districtId:id,districtName:district.nameTh});accessibleLayer(layer,label,action);S.hover?.bind(layer,()=>({level:country?'province':'district',id,feature,label:country?provinceName(id):district.nameTh}));}});record={group,children};S.navigationRecords.set(key,record);}
   record.group.addTo(S.navigationHitGroup);
  }
  // Coloured child polygons are visual evidence; only the broader hit boundary is tabbable here.
  for(const layer of S.provinceLayers.values())layer.getElement?.()?.setAttribute('tabindex','-1');
  for(const record of S.districtRecords.values())for(const layer of record.children)layer.getElement?.()?.setAttribute('tabindex','-1');
  for(const record of S.areaRecords.values())for(const layer of record.children)layer.getElement?.()?.setAttribute('tabindex','-1');
 }
 function sync(){
  if(!S.map||!S.panel||S.syncing)return;cancelViewportRefresh();S.syncing=true;
  try{readTokens();updateLanguage();S.panel.setAttribute('aria-busy',String(!!Y.loading));if(Y.loading){S.hover?.clear();S.navigationHitGroup?.clearLayers();S.districtGroup.clearLayers();S.areaGroup.clearLayers();clearPoints();S.draftGroup.clearLayers();setMessage(text('กำลังเปลี่ยนชุดข้อมูล · คงมุมมองแผนที่เดิม','Switching dataset; retaining map view'));return;}
   if(Y.loadError){S.hover?.clear();S.navigationHitGroup?.clearLayers();S.districtGroup.clearLayers();S.areaGroup.clearLayers();clearPoints();S.badgeGroup.clearLayers();S.draftGroup.clearLayers();for(const layer of S.provinceLayers.values()){layer.setStyle({fill:false,fillColor:value('--no-result'),fillOpacity:1,opacity:1,dashArray:'6 4'});layer.unbindTooltip?.();layer.bindTooltip(esc(text('ข้อมูลธุรกิจยังไม่พร้อม ไม่ตีความว่าไม่มีทำเล','Industry data unavailable; absence is not inferred')));}const stats=S.panel.querySelector('[data-workspace-map-stats]');if(stats)stats.textContent=text('ข้อมูลธุรกิจยังไม่พร้อม','Industry data unavailable');setMessage(text('เปลี่ยนชุดข้อมูลไม่สำเร็จ ยังไม่แสดงผลของแบรนด์ก่อนหน้า','Dataset switch failed. Previous-brand results are not displayed.')+' '+Y.loadError);return;}if(Y.route==='criteria'&&criteriaErrors(draft).length){setMessage(text('ตรวจค่าของเกณฑ์ก่อน แผนที่คงผลล่าสุดที่ใช้ได้','Check invalid criteria. The map retains the last valid result.'));S.panel.setAttribute('aria-busy','false');return;}const changedRoute=S.lastRoute!==Y.route;if(changedRoute&&Y.route!=='criteria')S.layer='eligible';S.lastRoute=Y.route;
   const s=snapshot(),rows=displayedRows(s).filter(areaMatchesNavigation);S.lastSnapshot=s;prepareAnalysis(s);S.badgeGroup.clearLayers();for(const [code,layer]of S.provinceLayers){const active=!S.nav.provinceCode||S.nav.provinceCode===code;layer.setStyle({color:value('--yl-border-strong'),weight:S.nav.provinceCode===code?2:1,fill:false,fillOpacity:1,opacity:active?1:0,dashArray:null});layer.unbindTooltip?.();if(S.nav.level==='country')layer.bindTooltip(esc(provinceName(code)),{sticky:true});const element=layer.getElement?.();if(element){element.setAttribute('aria-label',provinceName(code));element.setAttribute('tabindex',S.nav.level==='country'?'0':'-1');}}
   drawDistricts(rows,s);
   const areas=drawAreas(rows,s),points=drawPoints();global.YolkTierStyle?.ensureDefs(S.map);drawNavigationTargets();S.lastAreaCounts=areas;drawDraftPoint();updateChrome(s,rows,points.shown,points.total,areas.shown,areas.total);updateAnalysisChrome(s,rows);setMessage(S.hierarchyError||S.fineErrors.get(S.nav.provinceCode)?(S.hierarchyError||text('ขอบเขตทำเลบางส่วนโหลดไม่ได้ ไม่ใช้กรอบพิกัดเป็นสีแทน','Some location boundaries failed. Source extents are not substituted as coloured polygons')):S.hierarchyPromise?text('กำลังอ่านขอบเขตอำเภอและทางเชื่อมทำเล…','Loading district boundaries and location crosswalk…'):S.finePending.has(S.nav.provinceCode)?text('กำลังอ่านขอบเขตแขวง/อปท. ต้นทาง…','Loading source Khwaeng/local-authority polygons…'):Y.pointState==='error'?text('โหลดรายการสาขาไม่สำเร็จ ยังไม่ตีความว่าไม่มีสาขา','Branch inventory failed to load; absence is not inferred'):S.analysis?.kind==='supply'&&S.nav.level==='country'&&S.nativeDistrictErrors.has(Y.industry)?text('ยอดสาขาระดับอำเภอยังไม่พร้อม ไม่ใช้ยอดทำเลบวกแทน','District branch totals unavailable; fine counts are not summed as a substitute'):S.analysis?.kind==='supply'&&S.nativeDistrictPending.has(Y.industry)?text('กำลังอ่านยอดสาขาระดับอำเภอ…','Loading native district branch totals…'):global.YOLK_RUNTIME.geometryState==='error'?text('โหลด Polygon ไม่สำเร็จ ใช้กรอบพิกัดต้นทางแทนโดยติดป้ายชัดเจน','Polygon load failed; source extents remain explicitly labelled'):Y.pointState==='loading'?text('กำลังอ่านรายการสาขา…','Loading branch records…'):S.provinceError||S.tileError||'');S.panel.setAttribute('aria-busy','false');
   if((S.nav.level==='location'||Y.route==='poi')&&!global.YOLK_RUNTIME.pointCache.has(Y.industry)&&Y.pointState!=='loading'&&Y.pointState!=='error'&&typeof ensureSourcePoints==='function')Promise.resolve(ensureSourcePoints()).then(sync);
   if((S.nav.level!=='country'||S.focusedArea)&&!global.YOLK_RUNTIME.geometryState&&typeof ensureSourceGeometry==='function')Promise.resolve(ensureSourceGeometry()).then(sync);
   if(S.nav.provinceCode&&S.hierarchy)loadFine(S.nav.provinceCode);
  }finally{S.syncing=false;}
 }
 function home(){return navigate({level:'country'},{notify:false});}
 function focusArea(id){const a=AREA_INDEX.get(id);if(!a)return false;const ids=areaDistricts(a),districtId=ids.includes(S.nav.districtId)?S.nav.districtId:ids.length===1?ids[0]:'';navigate({level:'location',provinceCode:a.province,districtId,areaId:id},{notify:false});return !!(usableGeometry(a)||extentBounds(a.extent3857));}
 async function focusPoi(id){S.viewInteracted=true;const ticket=++S.focusTicket,key=criteriaContextKey(),route=Y.route;let p=(Y.pois||[]).find(p=>p.id===id);if(!p&&typeof ensureSourcePoints==='function'){await ensureSourcePoints();if(ticket!==S.focusTicket||key!==criteriaContextKey()||route!==Y.route)return false;p=(Y.pois||[]).find(p=>p.id===id);}if(!p||!validPoint(p)||!S.map){setMessage(text('รายการนี้ยังไม่มีพิกัดที่แสดงได้','No usable coordinates for this record'));return false;}const a=AREA_INDEX.get(p.area),ids=areaDistricts(a),districtId=ids.includes(S.nav.districtId)?S.nav.districtId:ids.length===1?ids[0]:'';S.nav={level:'location',provinceCode:String(p.province||a?.province||''),districtId,districtName:S.districtIndex.get(districtId)?.nameTh||'',areaId:a?.id||''};S.focusedPoi=id;S.focusedArea=a?.id||'';S.map.setView([p.lat,p.lng],Math.max(S.map.getZoom(),15),{animate:false});sync();return true;}
 function setBasemap(style){if(!S.map||!['simplified','satellite','detailed'].includes(style))return false;S.basemap=style;S.tileError='';S.panel.dataset.workspaceBasemap=style;if(S.tileLayer){S.tileLayer.off();S.map.removeLayer(S.tileLayer);}const satellite='https://wmts.terrascope.be/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=esa-worldcover-s2rgbnir-10m-2021-v2_tcc&STYLE=default&TILEMATRIXSET=EPSG%3A3857&TILEMATRIX={z}&TILECOL={x}&TILEROW={y}&FORMAT=image%2Fpng&TIME=2021-01-01';S.tileLayer=global.L.tileLayer(style==='satellite'?satellite:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',{minZoom:3,maxZoom:19,maxNativeZoom:style==='satellite'?14:19,noWrap:true,keepBuffer:1,updateWhenIdle:true,attribution:style==='satellite'?'ESA WorldCover / Copernicus Sentinel-2 2021 · 10 m · <a href="https://docs.terrascope.be/Developers/WebServices/OGC/WMTSv2.html" target="_blank" rel="noopener">Terrascope</a>':'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> · <a href="https://www.geoboundaries.org/" target="_blank" rel="noopener">geoBoundaries</a> province context'}).addTo(S.map);S.tileLayer.on('tileerror',()=>{S.tileError=text('แผนที่พื้นหลังบางส่วนโหลดไม่ได้ ชั้นข้อมูลยังดูได้','Some basemap tiles failed; data layers remain usable');setMessage(S.tileError);});const select=S.panel.querySelector('[data-workspace-basemap]');if(select)select.value=style;return true;}
 function pending(){S.panel?.setAttribute('aria-busy','true');setMessage(text('กำลังคำนวณผลแบบร่าง…','Updating draft results…'));}
 function setLayer(layer){if(!Object.hasOwn(layerLabels,layer))return false;S.layer=layer;sync();return true;}
 function previewBaselineDraft(){setLayer('eligible');return snapshot();}
 function mount(options={}){
  Object.assign(S.callbacks,options);if(S.map){S.map.invalidateSize({pan:false});sync();return S.map;}
  const host=global.document.getElementById('workspace-map');if(!host)return null;S.host=host;S.panel=global.document.getElementById('workspace-map-panel')||host.parentElement;
  if(!S.panel.querySelector('[data-workspace-map-toolbar]')){host.insertAdjacentHTML('beforebegin',`<div class="workspace-map-toolbar" data-workspace-map-toolbar><div class="workspace-map-heading"><h2 data-workspace-map-title>${text('ไข่แดงและช่องว่างสาขา','Yolks and branch gaps')}</h2><div class="workspace-map-stats" data-workspace-map-stats aria-live="polite"></div></div><button type="button" class="workspace-map-controls-toggle" data-workspace-controls-toggle aria-controls="workspace-map-options" aria-expanded="false" aria-label="${text('ตั้งค่าแผนที่','Map options')}">${icon('layers')}<span data-workspace-controls-label>${text('ตั้งค่าแผนที่','Map options')}</span></button><div id="workspace-map-options" class="workspace-map-actions workspace-map-options"><label><span data-workspace-layer-label>${text('มุมมองแผนที่','Map view')}</span><select data-workspace-map-layer aria-label="${text('มุมมองแผนที่','Map view')}">${Object.entries(layerLabels).map(([id,label])=>`<option value="${id}">${text(...label)}</option>`).join('')}</select></label><label><span data-workspace-basemap-label>${text('แผนที่พื้นหลัง','Basemap')}</span><select data-workspace-basemap aria-label="${text('แผนที่พื้นหลัง','Basemap')}"><option value="simplified">${text('เรียบง่าย','Simplified')}</option><option value="satellite">${text('ดาวเทียม','Satellite')}</option><option value="detailed">${text('รายละเอียด','Detailed')}</option></select></label><button type="button" data-workspace-map-back hidden aria-label="${text('กลับระดับก่อนหน้า','Back one level')}">${icon('arrow_back')}</button><button type="button" data-workspace-map-home aria-label="${text('ดูทั้งประเทศ','Show nationwide')}">${icon('map')}</button><button type="button" data-workspace-map-focus hidden>${text('กลับจุดที่เลือก','Fit selection')}</button></div></div><div class="workspace-analysis-caption" data-workspace-analysis-caption></div><nav class="workspace-map-breadcrumbs" data-workspace-map-breadcrumbs aria-label="${text('ลำดับพื้นที่','Map hierarchy')}"></nav><div class="workspace-map-district-choices" data-workspace-district-choices hidden></div><div class="workspace-map-poi-layers" data-workspace-poi-layers role="group" aria-label="${text('ชั้นข้อมูลสาขา','Branch layers')}">${[['own','O','เรา','Our stores'],['competitor','C','คู่แข่ง','Competitors'],['unverified','U','รอตรวจ','To verify']].map(([id,symbol,th,en])=>`<button type="button" data-workspace-poi-layer="${id}" aria-pressed="true"><b>${symbol}</b><span>${text(th,en)}</span></button>`).join('')}</div>`);
   host.insertAdjacentHTML('afterend',`<div class="workspace-map-footer"><div data-workspace-map-legend class="workspace-map-legend"></div><p data-workspace-map-note></p><details class="workspace-map-evidence"><summary data-workspace-map-evidence-label>${text('พิกัดและขอบเขตที่แสดง','Coordinates & boundaries shown')}</summary><p data-workspace-map-counts></p></details><p data-workspace-map-status role="status" aria-live="polite"></p></div>`);
  }
  setControlsOpen(false);
  if(!global.L){setMessage(text('แผนที่ยังไม่พร้อม · รายการข้อมูลยังใช้งานได้','Map unavailable; data lists remain usable'));return null;}
  S.map=global.L.map(host,{zoomControl:false,scrollWheelZoom:true,minZoom:3,maxZoom:19,zoomSnap:.25,zoomDelta:.5,attributionControl:true,preferCanvas:false}).setView([13.2,101],5);host.setAttribute('tabindex','0');host.setAttribute('aria-label',text('แผนที่โต้ตอบ เลื่อนและซูมเพื่อสำรวจทำเล','Interactive map. Pan and zoom to explore locations'));
  global.L.control.zoom({position:'bottomleft',zoomInTitle:text('ซูมเข้า','Zoom in'),zoomOutTitle:text('ซูมออก','Zoom out')}).addTo(S.map);global.L.control.scale({position:'bottomleft',imperial:false,maxWidth:100}).addTo(S.map);
  setBasemap('simplified');
  S.districtGroup=global.L.layerGroup().addTo(S.map);S.areaGroup=global.L.layerGroup().addTo(S.map);S.pointGroup=global.L.layerGroup().addTo(S.map);S.badgeGroup=global.L.layerGroup().addTo(S.map);S.draftGroup=global.L.layerGroup().addTo(S.map);S.navigationHitGroup=global.L.layerGroup().addTo(S.map);S.hover=global.YolkMapHover?.create({map:S.map,L:global.L,token:()=>value('--yl-map-active')});
  S.panel.dataset.workspacePopupOpen='false';S.map.on('popupopen',()=>{S.panel.dataset.workspacePopupOpen='true';});S.map.on('popupclose',()=>{S.panel.dataset.workspacePopupOpen='false';});
  S.panel.addEventListener('change',event=>{if(event.target.matches('[data-workspace-map-layer]'))setLayer(event.target.value);if(event.target.matches('[data-workspace-basemap]'))setBasemap(event.target.value);});
  S.panel.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.hasAttribute('data-workspace-controls-toggle'))setControlsOpen(!S.controlsOpen);else if(b.hasAttribute('data-workspace-map-home'))navigate({level:'country'});else if(b.hasAttribute('data-workspace-map-back'))back();else if(b.dataset.workspaceDistrictChoice){const d=S.districtIndex.get(b.dataset.workspaceDistrictChoice);if(d)navigate({level:'district',provinceCode:d.provinceCode,districtId:d.id});}else if(b.dataset.workspaceNavLevel){const level=b.dataset.workspaceNavLevel;navigate({...S.nav,level});}else if(b.hasAttribute('data-workspace-map-focus')){if(S.focusedPoi)focusPoi(S.focusedPoi);else if(S.focusedArea)focusArea(S.focusedArea);}else if(b.dataset.workspacePoiLayer){S.show[b.dataset.workspacePoiLayer]=!S.show[b.dataset.workspacePoiLayer];sync();}else if(b.dataset.workspaceOpenPoi){const id=b.dataset.workspaceOpenPoi;if(S.callbacks.onPoi)S.callbacks.onPoi(id);else location.hash='poi/'+id;}});
  S.panel.addEventListener('keydown',event=>{if(event.key==='Escape'&&S.controlsOpen){event.preventDefault();setControlsOpen(false);S.panel.querySelector('[data-workspace-controls-toggle]')?.focus?.();}});
  S.map.on('moveend zoomend',queueViewportRefresh);S.map.on('dragstart',()=>{S.focusTicket++;S.viewInteracted=true;});global.document.addEventListener('yolk:themechange',sync);global.document.addEventListener('input',event=>{if(Y.route==='poi'&&['lat','lng'].includes(event.target.name)&&event.target.form?.id==='poi-form')sync();});if(global.ResizeObserver)new global.ResizeObserver(()=>{const height=S.host.clientHeight;if(Number.isFinite(height)&&height>0)S.host.style?.setProperty('--workspace-popup-max-height',Math.max(100,height-64)+'px');S.map.invalidateSize({pan:true,animate:false});for(const record of S.pointRecords.values())if(record.marker.isPopupOpen?.())record.marker.getPopup?.()?.update?.();}).observe(S.panel);
  sync();loadHierarchy();loadProvinces().then(()=>{if(S.map&&S.provinceGroup&&!S.focusedArea&&!S.focusedPoi&&S.map.getZoom()===5&&!S.viewInteracted)home();});return S.map;
 }
 global.YolkWorkspaceMap=Object.freeze({analysisState:()=>({state:S.analysis,fine:S.analysisFine,district:S.analysisDistrict,nativeLoading:S.nativeDistrictPending.has(Y.industry),nativeError:S.nativeDistrictErrors.get(Y.industry)||null}),mount,sync,home,navigate,back,getNavigation,navigationLabel,areaMatchesNavigation,poiMatchesArea,poiMatchesNavigation,focusArea,focusPoi,previewBaselineDraft,pending,setLayer,setBasemap,snapshot,tierClass,extentBounds,provinceSummary,visiblePoints,getState:()=>({mounted:!!S.map,controlsOpen:S.controlsOpen,layer:S.layer,focusedArea:S.focusedArea,focusedPoi:S.focusedPoi,provinceCount:S.provinceLayers.size,hierarchyReady:!!S.hierarchy,districtCount:S.districtData?.features?.length||0,navigation:getNavigation(),pointLimit:MAX_POINTS,areaLimit:MAX_AREAS})});
})(window);
